### ISSUE TITLE
Seaside 3 WAScreenshot>>uiProcess problem in Squeak installation

### ISSUE THREAD

**Issue by timrowledge** [SeasideSt/Seaside#1032]
In the seaside I have loaded right now - a very recent install - the `WAScreenshot >> #uiProcess` method tries to run

```smalltalk
  ^ UIManager default uiProcess
```

... which fails because UIManager does not implement this. The current Squeak images both 5.1 & 5.2 would do this with

```smalltalk
  ^ Project current uiProcess
```

@jbrichau suggests -

> this code is in a Pharo-specific package, which is included when loaded in Squeak but was never correctly adapted to work on it.
> 
> I see three options:
> - Extend Grease with the necessary abstractions for both platforms and the code in the package should be rewritten in terms of those abstractions
> - Create a Squeak-specific package for it and include that in the load for Squeak
> - Leave out this functionality when loading in Squeak

**Comment by marschall** [comment]
Fixed by #1156
