### ISSUE TITLE
Improvements to WAUrl >> #decodePercent:

### ISSUE THREAD

**Issue by marianopeck** [SeasideSt/Seaside#1042]
Hi guys, 

Pharo has built-in UTF-8 support, but on other dialects some parts of Seaside don't work without explicit conversion from/to UTF-8. One of those places is WAUrl >> decodePercent:. 

Aside from that, based on https://tools.ietf.org/html/rfc3986#section-2.1 when you use percent encoding, they are encoded as octects/bytes, hence always < 255. Else, we should signal WAInvalidUrlSyntaxError. So, what about these 2 changes:

	WAUrl >> decodePercent: aString
	    "percent decodes the given String"

	    | input output char |

	    input := aString readStream.
	    output := WriteStream on: (String new: aString size).
	    [input atEnd] whileFalse: [
	        char := input next.
	        output nextPut: (
	            char = $+
	                ifTrue: [Character space]
	                ifFalse: [
	                    char = $%
	                        ifTrue: [self convertNextCharacterIn: input decodedFrom: aString]
	                        ifFalse: [char]])].
	    ^(GRCodec forEncoding: 'utf-8') decode:  output contents

And: 

	convertNextCharacterIn: input decodedFrom: aString

	    "Based on https://tools.ietf.org/html/rfc3986#section-2.1 when you use
	    percent encoding, they are encoded as octects/bytes, hence always < 255."

	    | firstByte secondByte codePoint |

	    firstByte :=
	        input atEnd
	            ifTrue: [WAInvalidUrlSyntaxError signal: aString]
	            ifFalse: [input next asUppercase digitValue].
	    secondByte :=
	        input atEnd
	            ifTrue: [WAInvalidUrlSyntaxError signal: aString]
	            ifFalse: [input next asUppercase digitValue].
	    codePoint := firstByte * 16 + secondByte.
	    ^codePoint > 255
	        ifTrue: [WAInvalidUrlSyntaxError signal: aString]
	        ifFalse: [Character codePoint: codePoint]

What do you think?

**Comment by marianopeck** [comment]
One doubt about the line `^(GRCodec forEncoding: 'utf-8') decode:  output contents` is if this is *always* de case (via RFC or something) or it could somehow depend on certain configuration? If the latter...then we can't hardcode UTF-8.

**Comment by marianopeck** [comment]
Thinking a bit more with the help of Adriaan Van Os, I retract of adding the `^(GRCodec forEncoding: 'utf-8') decode: output contents`. That should already happen in `WAUrl>>decodedWith:` and decoding twice will be wrong. Finally, UTF-8 is not even *always* the case. Just the default in HTML5 according to [this link](https://www.w3schools.com/tags/ref_urlencode.asp).

**Comment by marschall** [comment]
`#decodePercent:` does just this, percent decoding. Handling the encoding happens in `WAUrl #decodedWith:` with the codec.

**Comment by adriaon** [comment]
Example of problametic url: localhost:8088/config%2Fetc%2Fhosts

**Comment by marschall** [comment]
Superseded by #1157
