### ISSUE TITLE
Remove everything related to Pharo < 4 from baseline

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#1044]
Because now Seaside is only for Pharo 4+

**Comment by jecisc** [comment]
We can also remove packages used only for Pharo < 5 and merge the packages like Javascript-Pharo20-Core with Javascript-Pharo-Core

**Comment by jbrichau** [comment]
Right. I meant 4 and 5. 
We added 4 back because we could make the loading and testing work with metadataless filetree anyway.

I'm not sure renaming the `Pharo20` package is a good idea when people would be upgrading their existing Seaside install in a Pharo 6 (or even 7). What happens when you first load master and then your branch?

**Comment by jecisc** [comment]
It will probably move all the methods to the new package and leave an empty Pharo20 package I guess.

**Comment by jecisc** [comment]
I find it a little confusing to have a package named "Pharo" that is only loaded in squeak and a package named "Pharo20" that is the default one for Pharo.

**Comment by jbrichau** [comment]
I agree and it would be great to have that fixed. I'll run over the changes and integrate it.

**Comment by jecisc** [comment]
My PR is only a first step. Since it impacts multiple smalltalk and a complex baseline I wanted to do it by steps.

**Comment by jecisc** [comment]
If you prefer a PR with all the changes at once to review tell me and I'll do the other changes.

**Comment by jbrichau** [comment]
Steps are good. Hold on a moment as I rename package extensions for Pharo7...

**Comment by marschall** [comment]
The only thing referencing the old versions is the gettext baseline, this is addressed by #1131 .

And Javascript has a different baseline for Pharo 7.x so I'm closing this.
