### ISSUE TITLE
Status of Seaside-InternetExplorer

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#1068]
Currently, the package `Seaside-InternetExplorer` is referenced only by the 'Tests' group, but no non-test group of the baseline reference it. So currently it's dead code if you do not load tests. 

Two solutions:
- This package is obsolete: then we sould remove it with its tests
- This package is missing in the core group: then we need to add it

Since no-one never complained about that, I guess it's an obsolete package. Any information or though @jbrichau ?

**Comment by marschall** [comment]
It is intended as a package that people can load if they need IE specific extensions. We assume these cases are rare so it is not in a group or loaded by default.

**Comment by jecisc** [comment]
But if it is not in a group or in default, then it's not loadable without a hack.

**Comment by jbrichau** [comment]
If I remember correctly, Metacello allows you to specify a single package as well, just like you specify a group. I would not consider that a hack.

What it does show is that we need to document it.

**Comment by jecisc** [comment]
Ok, I had the impression it was a bad practice to reference packages of other repositories and not projects/goups. 

But maybe it's fine for this kind of case.

**Comment by jecisc** [comment]
Should I keep this issue opened to add documentation?

**Comment by jbrichau** [comment]
I added this to https://github.com/SeasideSt/Seaside/wiki/Seaside-Load-Groups-and-Packages
