### ISSUE TITLE
Possibly remove WAPackagingTest

### ISSUE THREAD

**Issue by theseion** [SeasideSt/Seaside#1077]
I'm not familiar with the mechanism behind GRPackage but WAPackagingTest doesn't make any sense in its current form.

**Comment by marschall** [comment]
GRPackage has a way to track dependencies, this predates Metacello and over the years has no longer been properly maintained tested.
I think it would make sense the remove `WAPackagingTest` and remove the dependency tracking in `GRPackage` and have Metacello as our primary source of dependency tracking.

**Comment by theseion** [comment]
This issue is on hold. As stated in https://github.com/SeasideSt/Grease/pull/72, we'll investigate what parts of GRPackage are still in use.

**Comment by jbrichau** [comment]
Removing the WAPackagingTest
