### ISSUE TITLE
WAAbstractFileLibrary should use application/javascript for *.js, not application/x-javascript

### ISSUE THREAD

**Issue by ThomasBrodt** [SeasideSt/Seaside#1078]
WAAbstractFileLibrary still uses application/x-javascript instead of application/javascript as mime type for files with .js extension. application/javascript is official as in RFC4329.

This is for Seaside 3.2. and the current code tab on github.
See initializing method #defaultMimeTypes

**Comment by theseion** [comment]
Thanks! Nice find.
