### ISSUE TITLE
Merge Comet-Core and Comet-Pharo-Core

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#1082]
From what I can read in the baseline, Comet is only loadable in Squeak and Pharo. Also, both Squeak and Pharo also load Comet-Pharo-Core.

We can then merge Comet-Core and Comet-Pharo-Core since those two packages are always loaded together.

**Comment by theseion** [comment]
From what I see, Comet is actually only loaded for Pharo 1.x (as "Comet Examples").
@jbrichau @marschall Is Comet even supported beyond Pharo 1.x? If not we could remove it completely from GitHub.

**Comment by jecisc** [comment]
Where did you see it was only for Pharo 1? Because It loads in Pharo 7. But since I don't know what Comet is, I don't know if it works after loading it in Pharo 7.

And also what about Squeak?

**Comment by jbrichau** [comment]
Comet is a group you can specify in your project's baseline, so I don't see why 'Comet is not loadable'. 
Seaside is also ported to Visualworks and VA Smalltalk. Some of the package structure is sometimes organized so porters of other dialects can easily replace the platform-specific parts. For Comet, I'm not sure if this is the case, but the Pharo-specific parts are in the Pharo package.

I don't agree to break this separation between Core and Pharo-specific parts in the Comet codebase.

**Comment by jecisc** [comment]
Ok, I did not know that this project was also related to other Smalltalk than Pharo, Squeak and Gemstone. I only saw that in this project Comet was always loaded with Comet-Pharo. 

I'll close the PR.
