### ISSUE TITLE
Load Zinc adapter in the default group instead of requiring all users to load it specifically

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Seaside#1093]
Users have to explicitly load the Zinc adaptor themselves when using Seaside. E.g.:

```
Metacello new
 baseline:'Seaside3';
 repository: 'github://SeasideSt/Seaside:master/repository';
 load: #(default Zinc)
```
Using Seaside without an adaptor is useless, especially if you are new to Seaside.

Instead, we should load the Zinc Adaptor in the default group.

**Comment by jecisc** [comment]
Zinc is loaded by default in Pharo in #baselinewelcome:

I guess it's not the right place to add it there. It should maybe be in #baselinepharo: 

Anyway, it should not be loaded by default in Squeak I guess. I remember someone saying Zinc is not the adaptor to load in Squeak.

**Comment by jbrichau** [comment]
No, it should online be in Pharo. However, when I executed the basic load instructions, I did not get Zinc by default. I will check again.

But It’s indeed only for Pharo.

**Comment by jecisc** [comment]
This is weird because I get it with the default group. 

Anyway, I think that the declaration should not be in Welcome but is #baselinepharo:

**Comment by jbrichau** [comment]
You're right. It does get loaded with the default. Now, I wonder why I so often got an image without the necessary adaptor loaded... anyhow..

The `baselineOfAdapators` is a better place to specify the default adaptor to load on each platform. I will put it there.

**Comment by jbrichau** [comment]
Changed in https://github.com/SeasideSt/Seaside/pull/1094
