### ISSUE TITLE
3.3 changelog typo, perhaps

### ISSUE THREAD

**Issue by tcj** [SeasideSt/Seaside#1122]
On the [3.3.0 changelog](https://github.com/SeasideSt/Seaside/wiki/Seaside330Changelog) I wonder if the following sentence:

> Instead #handleDefault: is _not_ sent to the application.

Should instead read:

> Instead #handleDefault: is _now_ sent to the application.

**Comment by jbrichau** [comment]
Correct. Thanks for noticing and reporting!
