### ISSUE TITLE
Zinc-Seaside breaks on ZnUrl pathSegment containing `$/`

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Seaside#1129]
The change in Zinc https://github.com/svenvc/zinc/commit/d962746ae9688550d0c826b9103018a87789afb1 breaks an assumption in Zinc-Seaside because pathSegments now can contain single chars (which is the case for a `$/` in the pathSegments.

**Comment by jbrichau** [comment]
The problem is this line of code: https://github.com/SeasideSt/Seaside/blob/a9b91bbc55fbfdb016427bc39c6bb2385009cb81/repository/Zinc-Seaside.package/ZnZincServerAdaptor.class/instance/requestUrlFor..st#L12

**Comment by noha** [comment]
#/ needs to be changed to $/

**Comment by jbrichau** [comment]
@noha Yes, I'm on it ;) But it takes more time to write a test for it than fix the bug itself.

**Comment by marschall** [comment]
I wonder whether something like this would be easier to understand and less error prone

```
	zincUrl hasPath ifTrue: [
		zincUrl isDirectoryPath
			ifTrue: [
				"last path segment is $/ or #/"
				zincUrl pathSegments allButLastDo: [ :each |
					seasideUrl addToPath: each ].
				seasideUrl slash: true ]
			ifFalse: [
				seasideUrl addAllToPath: zincUrl pathSegments ] ].
```
if we don't care about the copy we could even use something like this

```
	zincUrl hasPath ifTrue: [
		| segments |
		segments := zincUrl isDirectoryPath
			ifTrue: [ zincUrl pathSegments allButLast "last path segment is $/ or #/" ]
			ifFalse: [ zincUrl pathSegments ].
		seasideUrl addAllToPath: segments.
		seasideUrl slash: zincUrl isDirectoryPath ].
```
