### ISSUE TITLE
Gettext integration is broken (on Pharo 7)

### ISSUE THREAD

**Issue by brunobuzzi** [SeasideSt/Seaside#1133]
Check:
http://forum.world.st/Loading-Gettext-on-already-installed-Seaside-tp5100353.html

**Comment by marschall** [comment]
Don't forget to fix #1053 as well.

**Comment by vitormcruz** [comment]
I had this problem today, when loading Metacello states that 'Gettext' don't exits. I just figure out what I was happening by looking at the Seaside Baseline and there there is not pharo 8  or 9 tag.

Gettex is not the correct way of doing i18n with seaside anymore?

**Comment by marschall** [comment]
@jbrichau has this been fixed by ##1244

**Comment by jbrichau** [comment]
@marschall indeed. Forgot to close this ticket.
