### ISSUE TITLE
Do not use #replaceAll:with: with possible literal Strings

### ISSUE THREAD

**Issue by marianopeck** [SeasideSt/Seaside#1134]
Hi, 

In Pharo, `String` literals (of a `CompiledMethod`) are mutable (which I personally believe its a bad thing). But anyway, other dialects have immutable literals. So...doing a `#replaceAll:with:` over a immutable String would fail.

There are 2 methods in Seaside: `#addFileAt:relativeToRootDirectory:` and `asFileAndFoldername:` that are sending the message `#replaceAll:with:` to a `String` that quite likely came from a literal. 

I suggest to change that to be `#copyReplaceAll:with:` or make a copy of the String: `filename copy replaceAll: $/ with: pathSeparator first.`

Thanks

**Comment by marschall** [comment]
`WAFileMetadataLibrary >> #asFileAndFoldername:` already sends `#copyReplaceAll:with:`

**Comment by marschall** [comment]
`WAFileMetadataLibrary class >> #addFileAt:relativeToRootDirectory:` sends `#replaceAll:with:` to the result of `#allButFirst:` so I don't think this can be a literal.
