### ISSUE TITLE
v3.2.5 Seaside-Core.package/GRPlatform.extension/instance/seasideVersion.st shows 3.2.2

### ISSUE THREAD

**Issue by rjsargent** [SeasideSt/Seaside#1143]
I see that Seaside-Core.package/GRPlatform.extension/instance/seasideVersion.st answers GRVersion major: 3 minor: 2 revision: 2 even though there have been a number of changed methods between 3.2.2 and the latest 3.2.5.

It's not really a problem, but it is potentially messy, if one were to try to rely on this method. If there were ever a new 3.2.x, it would be nice to see this updated. Or is there a policy the determines when this method gets advanced?

**Comment by jbrichau** [comment]
Hi @rjsargent 
Sorry about that. It's often forgotten. 
I need to see about a test that can verify this in the future...

Btw, why are you using an older version? It should be easy to upgrade to 3.3.x
