### ISSUE TITLE
Remove duplicated code in `remoteAddressFromRequest:` implementations

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Seaside#1152]
#remoteAddressFromRequest: should be unified with WAIPSessionTrackingStrategy>>remoteAddressFromRequest: aRequest.

If we're at it, we should probably also extend it to include the new standard header Forwarded (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded)

**Comment by marschall** [comment]
The code is buggy anyway, I don't think the `forwarded-for` branch works. The header is called `forwarded` and has a different syntax.
