### ISSUE TITLE
URL parsing should validate percent are hex

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Seaside#1157]
We should validate percent values are valid hex, for example `%ZZ` should not be valid.

**Comment by gcotelli** [comment]
I've finally found the problematic url that leads us to open #1042. It was a Windows network scanning tool sending `%NETHOOD%` in the url.

**Comment by marschall** [comment]
@gcotelli that makes sense parsing `%NE` would have given you something larger than 255.

**Comment by marschall** [comment]
Closed by #1158
