### ISSUE TITLE
Problem installing on linux & Pharo 7 (both x64)

### ISSUE THREAD

**Issue by C0ldS0b3r** [SeasideSt/Seaside#1176]
Hi;
With Pharo 7 
A. using this method gave the error ```WAPharoEncoder```

```
Gofer new
    url:'http://www.smalltalkhub.com/mc/Seaside/MetacelloConfigurations/main';
    package: 'ConfigurationOfSeaside3';
    load.
((Smalltalk at: #ConfigurationOfSeaside3) project version: #stable) load: 'CI'.
```

```
This package depends on the following classes:   WAPharoEncoder 
```

B. using this method would cause the whole Pharo windows to close unexpectedly.
```
Metacello new
 baseline:'Seaside3';
 repository: 'github://SeasideSt/Seaside:master/repository';
 load
```

All done on Fresh extracted folder of Pharo launcher on linux
```
Linux C0ld 5.2.11-desktop #1 SMP Thu Aug 29 15:52:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
 ****Also:
Installing it via Project Catalog errors with "something went wrong";

**Comment by marschall** [comment]
> Hi;
> With Pharo 7
> A. using this method gave the error `WAPharoEncoder`
> 
> ```
> Gofer new
>     url:'http://www.smalltalkhub.com/mc/Seaside/MetacelloConfigurations/main';
>     package: 'ConfigurationOfSeaside3';
>     load.
> ((Smalltalk at: #ConfigurationOfSeaside3) project version: #stable) load: 'CI'.

I don't think this is supposed to work on Pharo 7.

> B. using this method would cause the whole Pharo windows to close unexpectedly.
> 
> ```
> Metacello new
>  baseline:'Seaside3';
>  repository: 'github://SeasideSt/Seaside:master/repository';
>  load
> ```

That is the recommended way for Pharo 7 that is supposed to work. All Pharo windows closing sounds like a VM crash. If you launch from the command line do you get any log messages in the console? Do you have any log files in either the Pharo Launcher oder Seaside Image folder?

> ****Also:
> Installing it via Project Catalog errors with "something went wrong";

I don't think this is supposed to work either.

**Comment by C0ldS0b3r** [comment]
Hello.
The problem was with Pharo and I would try to explain as best as I could:
In linux, the error ```LibGit2-init``` is about the git library. but it may be something behind this.
if your git libraries is in order, then you should install a package that gives you ```libcurl-gnutls.so```.
I discover that by running ```pharo-launcher``` in terminal. 
```

ioLoadModule(/opt/pharo/bin/../lib/pharo/5.0-201901231209/libgit2.so):
  libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
``` 
If your linux distro doesn't  provide ```libcurl-gnutls.so``` you should patch ```curl``` source with gnutls patch. then build and install it in your library directory e.g ```/usr/lib64/```.(with the patch com
after doing all  and adding ssh key to ssh-agent :
```ssh-add ~/.ssh/id_rsa```

I would got exception in the middleof installing seaside on pharo 7. So I choose the Pharo 8 development image and it did the job.

**Comment by victornoel** [comment]
@C0ldS0b3r good find, on archlinux, installing the package libcurl-gnutls solved the problem.

**Comment by marschall** [comment]
Closing as it is a Pharo issue.
