### ISSUE TITLE
zinc path segment is Character instead of String -> Character DNU indexOf:

### ISSUE THREAD

**Issue by SabineMa** [SeasideSt/Seaside#1178]
I have the situation that a ZincRequest has a Character $/ as pathSegment and not a String. See screenshot below. Adding `asString` to the element would fix it. 

	 
```
zincUrl hasPath
		ifTrue: [ zincUrl pathSegments
				do: [ :each | 
					each asString = #/
						ifFalse: [ seasideUrl addToPath: each ] ].
			seasideUrl slash: zincUrl isDirectoryPath ].
```

 

<img width="691" alt="Bildschirmfoto 2019-09-03 um 13 17 59" src="https://user-images.githubusercontent.com/13763544/64173489-b3786800-ce57-11e9-815f-7dca37107d7d.png">

**Comment by marschall** [comment]
Hello @SabineMa is it possible this is a duplicate of #1129 ?

**Comment by SabineMa** [comment]
Hi  Philippe @marschall,
sorry that I respond so late I am in holidays. Yes it is a duplicate. I close it here.
Sabine
