### ISSUE TITLE
Seaside v3.3.3 is broken due to changes in Grease

### ISSUE THREAD

**Issue by gcotelli** [SeasideSt/Seaside#1179]
This version has `Grease/master` as dependency in the baseline. But now that `fixCallbackTemps` is removed from Grease this Seaside version don't work anymore if you load it in a new image.

**Comment by marschall** [comment]
v3.3.4 references `Grease:v1.4.x` so it should be fixed

**Comment by jbrichau** [comment]
Loading an older version is indeed broken because Grease is no longer backwards compatible in the sense that it removed useless methods.

Upgrading to 3.3.4 should not be an issue however, if you are using 3.3.3 already.
