### ISSUE TITLE
WAPharoUrlEncoder does not encode WideString

### ISSUE THREAD

**Issue by mumez** [SeasideSt/Seaside#1181]
```
writeStream := '' writeStream.
enc := WAPharoUrlEncoder on: writeStream.
enc nextPutAll: (#[227 130 162 227 131 188 227 130 171 227 131 160 232 178 161 229 155 163]) utf8Decoded. "アーカム財団"
writeStream contents. "expects:  '%E3%82%A2%E3%83%BC%E3%82%AB%E3%83%A0%E8%B2%A1%E5%9B%A3'"
```
The above code causes SubscriptOutOfBounds error. (SubscriptOutOfBounds: 12451).

With ZnPercentEncoder, we can get the expected encoded string. So, why not delegating it? 
```
ZnPercentEncoder new encode: (#[227 130 162 227 131 188 227 130 171 227 131 160 232 178 161 229 155 163]) utf8Decoded. "returns:  '%E3%82%A2%E3%83%BC%E3%82%AB%E3%83%A0%E8%B2%A1%E5%9B%A3'
```

**Comment by marschall** [comment]
A WAUrlEncoder only does "percent encoding", string to byte encoding is done by a codec. To quote from the class comment of `WAUrlEncoder`:

> I do percent-encoding of parts (e.g. path segments and arguments) of a URI.
> 
> Additionally, a Codec is given the chance to encode the characters into bytes before being percent-encoded (see http://tools.ietf.org/html/rfc3986#section-2.5). This allows extended characters to be represented in URIs in, for example, UTF-8.

> With ZnPercentEncoder, we can get the expected encoded string. So, why not delegating it?

Because then Seaside would only work with Zinc
