### ISSUE TITLE
[VW] Bug in SeasideResponder requestFieldsFor:

### ISSUE THREAD

**Issue by ThomasBrodt** [SeasideSt/Seaside#1190]
I think I found a bug in the general conversion of a Visualworks SiouX request to a WARequest in class SeasideResponder.

I published a new version "3.2.0 - 1 + Test for bug in requestFieldsFor,thomasb" of Seaside-Tests-VisualWorks-Adaptors in the Cincom public repository to see the problem. There is a new test method #testRequestFieldsJsonPostRequest that fails with a corresponding request.

A special json content with critical characters leads to an error, so that the request doesn't even reach Seaside handling.

Can someone have a look please?

Thanks

**Comment by ThomasBrodt** [comment]
I do not completely understand what should happen, but if my guess is right, the method should take the request fields either from multipart encoded content in the body of the request, or from the url with &key=value scheme. But it tries to take the &key=value scheme approach for the body of the request. 
If the body is empty, there are no fields and there is no error, so fine with the error, but the query fields don't get added.
If the body is not empty, it tries to parse this arbitrary body content by = and decodes whatever it finds. 

Q: shouldn't it take the url in the second case instead of the body content?

As there is a queryData method in HttpRequest, you could write:
```
requestFieldsFor: aNativeRequest
	| fields |
	fields := WARequestFields new.
	aNativeRequest isMultipart
		ifTrue: [self postEncodedDataFrom: aNativeRequest keysAndValuesDo: [:key :value | fields at: key add: value]]
		ifFalse: [
			">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
			"self urlEncodedDataFrom: aNativeRequest contents keysAndValuesDo: [:key :value | fields at: key add: value]"
			aNativeRequest queryData
				do: [:eachAssociation | fields at: eachAssociation key add: eachAssociation value]
			"<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"].
	^ fields
```
OR, not using queryData (they differ a little bit in decoding properties)
```
requestFieldsFor: aNativeRequest
	| fields |
	fields := WARequestFields new.
	aNativeRequest isMultipart
		ifTrue: [self postEncodedDataFrom: aNativeRequest keysAndValuesDo: [:key :value | fields at: key add: value]]
		ifFalse: [
			">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
			"self urlEncodedDataFrom: aNativeRequest contents keysAndValuesDo: [:key :value | fields at: key add: value]"
			self urlEncodedDataFrom: aNativeRequest url query keysAndValuesDo: [:key :value | fields at: key add: value]
			"<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"].
	^ fields
```

**Comment by marschall** [comment]
The VW port is not maintained it this repository but by Cincom. I would recommend trying to contact somebody a Cincom.

**Comment by ThomasBrodt** [comment]
Thanks Philippe,
I've also opened a customer request at cincom for the issue.
I didn't know where to put the issue, so I took both approaches.
So we'll see what cincom will answer.
