### ISSUE TITLE
WAFlowClosureFunctionalTest fails when backtracking to the start component

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Seaside#1200]
Execute the `WAFlowClosureFunctionalTest` as follows:
1. Click 'Go'
2. You see '1'; Click 'Ok' 
3. You see '2'; Go Back (use browser back button)
4. You see '1'; Go Back (use browser back button)
5. (you are now back at the start); Click 'Go'
5. You see '1'; Click 'Ok' 
6. You see '2'; Click 'Ok' 
7. You see '3'; Click 'Ok' 
-> expected to get back at the start component, instead I see '2' again.

I traced back this error to commit https://github.com/SeasideSt/Seaside/commit/9ce93c881755ad6527b5acb969ac9f77b63fa216#diff-d57efbd343ccc5cbc67f5e75d82bf0ac which installs lazy initialization of the `WAComponent.decoration` instvar. Reinstating the lazy initialization solves the error:

```Smalltalk
WAComponen>>initialize
	super initialize.	
	decoration := WAValueHolder with: self 
```

An automated test `testFlowClosureFunctionalTest2` that verifies this scenario was added and fails since Seaside 3.3.0: https://travis-ci.org/github/SeasideSt/Seaside/jobs/690603824

**Comment by jbrichau** [comment]
Or.... maybe `WAFlowClosureFunctionalTest` should have implemented the `states` method..

```Smalltalk
states
	^ Array with: self
```

... which makes the test work as well. 👍 

Funny... I am wondering why this scenario goes wrong but others (where you do not go back to the root component) do not _and_ it is also fixed by reverting the lazy decoration initialization.

@marschall any thoughts?

**Comment by marschall** [comment]
I think reverting the commit is the better option. Otherwise everything that does an `#inform:` (or `#call:onAnswer:`) would have to implement `#states`.
