### ISSUE TITLE
Failed to serve SVG file, HTTP 500 error.

### ISSUE THREAD

**Issue by peterwang** [SeasideSt/Seaside#1205]
For example, svg files at http://localhost:8080/files/WADevelopmentFiles don't load, error with HTTP 500 and return "MessageNotUnderstood: ByteArray>> #isByteString".  This causes the Halos toolbar icons missing.

I am using Pharo on windows 10, here are the version info.

Pharo 8.0.0
Build information: Pharo-8.0.0+build.1124.sha.0932da82f08175e906b0e2a8052120c823374e9f (64 Bit)

Seaside 3.4.1

Thanks!

**Comment by jbrichau** [comment]
The svg files in `WADevelopmentFiles` were indeed still in binary format. 
Fix in https://github.com/SeasideSt/Seaside/commit/f8bb0de8e6afb62adea3e061e263b52799d53b77
