### ISSUE TITLE
controlPanelInfos set to (nil) adaptor when starting Seaside Control panel in Pharo v9 latest 64 bit

### ISSUE THREAD

**Issue by Whalehead99** [SeasideSt/Seaside#1219]
Getting an error when I try to load Seaside Control panel from the Tools menu in Pharo v9 (latest 64bit build).  I used this Metacello snippet to download & install Seaside (which went flawlessly this time... well, at least it showed no errors).  

Metacello new
 baseline:'Seaside3';
 repository: 'github://SeasideSt/Seaside:master/repository';
 load.

By running the following snippet, I can get the server to load:
ZnZincServerAdaptor startOn: 8080.

Attached is the error screenshot.  Ideas?

![Screen Shot 2020-08-11 at 5 27 33 PM](https://user-images.githubusercontent.com/60747610/89951215-0080c480-dbf9-11ea-8ec3-fc732a32f3d1.png)
  
Thanks,
Russ

**Comment by jbrichau** [comment]
Hi,
May I recommend you try with Pharo8 ? Since Pharo9 is still a moving target, errors like this are likely to happen.

**Comment by Whalehead99** [comment]
Thanks for the advice :)  I went to Pharo 9 as Spec 2 dev was being dev'd there and v8 was pretty buggy (for Spec2)... (sigh).  I had been using a previous v9 build w/Seaside and the console loaded fine.  Since the server will start without the console, I'll probably continue in v9.  Just working my way through tutorials and attempting to apply concepts to my own applications.  I haven't been able to figure out (yet) how to get a real looking/functioning button... if it looks like a button, it doesn't function... if I put an anchor in it, it will function, but then doesn't look like a normal button, lol.
