### ISSUE TITLE
WAWebDriverFunctionalTestCase tests failing in GemStone?

### ISSUE THREAD

**Issue by dalehenrich** [SeasideSt/Seaside#1221]
There have been issues with SmalltalkHub over the last week, that have prevented my travis job from passing, but as of last night, the SmalltalkHub site issues were resolved and now I;m seeing that [many (all?) of the WAWebDriverFunctionalTestCase tests are now failing for GemStone](https://travis-ci.org/github/GsDevKit/GsDevKit_home/jobs/721523220#L2965). 

Three weeks ago, [the tests were passing](https://travis-ci.org/github/GsDevKit/GsDevKit_home/jobs/717364658#L2830). 

I will be looking into this in a bit more detail this afternoon, but I can only guess that either there were recent changes to Seaside/Parasol code base or perhaps the chrome drivers have been updated?

I am not optimistic that I will figure this out on my own, so I'm submitting this issue:)

**Comment by jbrichau** [comment]
@dalehenrich its the chrome webdriver that needs updating. I had to do the same for other projects. This time, I will search for a way to do it automatically.

**Comment by dalehenrich** [comment]
Oh, good! Could you give me a pointer to the update? I've got some internal build scripts that need to be updated

**Comment by dalehenrich** [comment]
I don't see any code changes, so I'm assuming you haven't got the magic formula yet, so I'll be patient:)

**Comment by jbrichau** [comment]
Not much too it (see 9b44f60516c203a69e80776769a8f9642d72ece7), I just would want to do it automatically.
Just updating your chromedriver binary should fix your test problems.

**Comment by dalehenrich** [comment]
... ah, so it seems the chrome driver needs to somehow match the version of chrome installed on the machine? If so, then automatic detection would be useful! My laptop is not running with chrome 85 yet and the newer driver won't work which does make the universe much more complicated:)

**Comment by dalehenrich** [comment]
tests are now passing with the new chrome driver
