### ISSUE TITLE
The class GsContext is in both Seaside (Seaside-GemStone-Core) and Grease (Grease-GemStone-Core)

### ISSUE THREAD

**Issue by dalehenrich** [SeasideSt/Seaside#1223]
It looks like GsDevKit/Grease does not have GsContext and SeasideSt/Grease does have GsContext.

Since SeasideSt/Grease is going to be the primary Grease repo (finally - GsDevKit/GsdevKit#124) we need to remove the duplication is Seaside-GemStone-Core ...

**Comment by jbrichau** [comment]
I think GsDevKit/Grease is identical to SeasideSt/Grease since some time, no?
The class is there: https://github.com/GsDevKit/Grease/tree/master/repository/Grease-GemStone-Core.package/GsContext.class

It did get moved from Seaside to Grease because of https://github.com/SeasideSt/Grease/issues/40
(which is unfinished but is there since 2 years waiting for me to write a test and hit the close button :)

**Comment by dalehenrich** [comment]
@jbrichau the GLASS1 baseline has been using GsDevKit/Grease ... the switching of the git repository for existing GsDevKit_home installations is the sticking point ... and has gummed up the works for me ... I'm hoping that I will be able to come up with a satisfactory solution while I'm doing the work for 3.6.0, since I have to make changes in a couple of different places ... wish me luck:)

**Comment by dalehenrich** [comment]
@jbrichau ... I just figured out what the REAL issue is ... GLASS1 baseline requires Grease and GLASS1 can be used with both Seaside3.2 (where the change has not been made) and Seaside3.4 where the change HAS been made ...

I will need to think about the best way to resolve this particular issue ... since the change in Grease will impact which Seaside can be used ... sort of as GsContext is basically the same as well .. just moved ...

**Comment by dalehenrich** [comment]
@jbrichau the plot thickens as it looks like [Seaside-GemStone-Core package](https://github.com/SeasideSt/Seaside/tree/69837a66c516e722a9e30cd377c17c5abbbd573f/repository/Seaside-GemStone-Core.package/GsContext.class) still has the GsContext class present ... which means that you get dirty GemStone package "conflicts" when using SeasideSt/Grease ... and this was the issue I was trying to address ...

**Comment by dalehenrich** [comment]
@jbrichau ... both Grease (GsDevKit/Grease and SeasideSt/Grease) and Seaside have the GsContext class present and that is basically what this bug is about ... deciding exactly where GsContext belongs (Grease probably) and then removing it from Seaside ... also I am fixing dalehenrich/filetree#195 which means that finally GemStone will **properly** honor metadataless repositories ...

**Comment by jbrichau** [comment]
@dalehenrich I had lost track of the fact that there is indeed duplication between Seaside and Grease. It should indeed be removed from Seaside. 

Sorry, re-reading the title of the issue, this is what you meant to say al along, while I was focusing on your comment about the difference between GsDevKit/Grease and Seaside/Grease.

afaik, older Seaside versions can still use newer Grease versions, with the disadvantage that the GsContext class will be overwritten (+ they might need to patch `fixTemps` which is the only non-backwards compatible change to Grease that ever happened to my knowledge).

**Comment by dalehenrich** [comment]
fixTemps is a noop in BlockClosure for GemStone in the Squeak package ... so perhaps the fixTemps is only something that is needed by Pharo ... and wouldn't be in GsContext anyway ... or is there something else going on?

**Comment by dalehenrich** [comment]
As a point of reference I created the PR GsDevKit/Grease#17 as a comparison between GsDevKit/Grease and SeasideSt/Grease  to pinpoint the changes between the two projects ...

**Comment by dalehenrich** [comment]
My current plan is to continue to use GsDevKit/Grease with a merge of the latest SeasideSt/Grease .... this will reduce the chance for errors introduced by switching Grease git repositories midstream (the time to do consolidate on SeasideSt/Grease is when we convert GemStone to use Rowan ... starting with GemStone 3.7.x). [This travis build](https://travis-ci.org/github/dalehenrich/Seaside/builds/727443940) confirms that at least all of the tests are passing after removing GsContext from Seaside-GemStone-Core package ...

**Comment by jbrichau** [comment]
@dalehenrich catching back up here: so removing the GsContext class from the Seaside package should be sufficient, right?
I'll also wrap up the [pending task in Grease](https://github.com/SeasideSt/Grease/issues/40#issuecomment-441351770) that concerns this.

**Comment by dalehenrich** [comment]
I believe so ... I've been occupied by work at the GLASS1 level for the last week or so I haven't spent time with Seaside and 3.6.0 yet ... but getting rid of the duplication is one of the things that needs to happen ... I will be removing Swazoo2 for 3.6.x and beyond as well ... but I am at least a couple of days away from doing that:)
