### ISSUE TITLE
WAWebDriverFunctionalTestCase >> #testCookieFunctionalTest is failing for Squeak-5.2

### ISSUE THREAD

**Issue by dalehenrich** [SeasideSt/Seaside#1229]
I think this test has been failing for Squeak-5.2 for several months ... I am in the middle of getting tests to pass for 3.6.0 and I can make this test an expected failure (for Squeak) if desired, with this bug as a reminder that Squeak-5.2 isn't really running clean ... 

At the end of the day it would be nice to see green status, but it isn't that big of a deal - just annoying to have to manually look every time I see a travis failed email to verify that it is only Squeak-5.2 that is failing:)

**Comment by jbrichau** [comment]
I agree. I did a final cry for help from the Squeak community a couple of months ago and I had one reaction but it is not bringing any results. 

I suggest adding the entire squeak jobs to the allowed failures list on Travis.

**Comment by dalehenrich** [comment]
okay ... that will be in my next PR when I finish off the remaing faiiing tests for 3.6.0...
