### ISSUE TITLE
The 'One Click' image for Linux doesn't start

### ISSUE THREAD

**Issue by welblaud** [SeasideSt/Seaside#1236]
**Description**
When I try to start the Pharo image with `$ ./pharo` after unpacking the archive, terminal just logs `Directory of file does not exist`. That's strange, I am pretty sure it is there and it has proper rights set. It reminds me of a situation when I try to open binaries for another OSes.

**Screenshot**
![obrazek](https://user-images.githubusercontent.com/8298610/104742422-b1f8c880-574a-11eb-8a0e-4ec99eebf3f4.png)

**Comment by jbrichau** [comment]
Hi!
Sorry about the outdated website.

I recommend you start with a fresh Smalltalk image from Pharo and install it manually using the install scripts: https://github.com/SeasideSt/Seaside#load-seaside

This will get you a working install in no time.

The one-click image is not something we continue to support. So I am closing this issue, but do not hesitate to join the mailinglist or the Pharo Discord channels (https://github.com/SeasideSt/Seaside#load-seaside) for help.
