### ISSUE TITLE
error en la version de pharo 6.1

### ISSUE THREAD

**Issue by maximilianofni** [SeasideSt/Seaside#1245]
![Pharo_Tsp8wGtmQF](https://user-images.githubusercontent.com/17895688/112532458-9aac0c00-8d87-11eb-9062-7cfa5a328c90.png)

**Comment by jbrichau** [comment]
Hi, 

Your screenshot shows a GIT loading error, but it does not show how you got it. 
I recommend you enter into contact with the Pharo community to sort out your git loading issues. See https://pharo.org/community

In any case, as you can see from the [builds](https://github.com/SeasideSt/Seaside/runs/2229903281?check_suite_focus=true), the current version of Seaside is still loading and working in Pharo6.1
