### ISSUE TITLE
GemStone: seasideMimeDocument should be implemented in CharacterCollection

### ISSUE THREAD

**Issue by brunobuzzi** [SeasideSt/Seaside#1246]
The current implementation of `#seasideMimeDocument ` fail when GemStone return `aUnicode16` (or other related string class)  instead of `aString`.

**Comment by jbrichau** [comment]
@brunobuzzi do you have a scenario or testcase we can use? I'm wondering if a plaintext mime type is a good idea in case of a Unicode16 instance and also in what context you can end up with such an instance receiving the `seasideMimeDocument` message.

**Comment by brunobuzzi** [comment]
@jbrichau i will try to create a TestCase and see in which situation anUnicode16 receives the message
