### ISSUE TITLE
Pharo 9 GRPharoPlatform>>openDebuggerOn: is broken as it relies on removed api - Process>>debug:title:full: does not exist

### ISSUE THREAD

**Issue by tblanchard** [SeasideSt/Seaside#1269]
Running into this problem with Seaside3.latest on Pharo 9 with GRPharoPlatform>>openDebuggerOn:
openDebuggerOn: anError
    | process |
    process := Processor activeProcess.
    "If we are running in the UI process, we don't want to suspend the active process. The
    error was presumably triggered while stepping in the Debugger. If we simply immediately
    signal an UnhandledError, the debugger will catch this and display the signaling context.
    It isn't perfect or pretty but it works."
    (ProcessBrowser isUIProcess: process)
        ifTrue: [
            UnhandledError signalForException: anError ]
        ifFalse: [
            WorldState addDeferredUIMessage: [
                process
                    debug: anError signalerContext
                    title: anError description
                    full: true ].
            process suspend ]
Process>>debug:title:full: doesn't exist anymore.  Just subbing debugTitle: doesn't open a debugger cleanly.

**Comment by jbrichau** [comment]
This is in Grease and was fixed a while ago: https://github.com/SeasideSt/Grease/commit/85380c9de0d926c7a8e93df45957e5c30a832e14

Can you check why you have an older Grease?

**Comment by tblanchard** [comment]
I used last released version.  3.4.0.

This is the lastest, correct? 

spec 
		baseline:'Seaside3' with: [ spec repository: 'github://SeasideSt/Seaside:v3.4.0/repository'];
		project: 'Seaside3-Deployment' copyFrom: 'Seaside3' with: [ spec loads: #(Core Zinc JSON REST Email Javascript JQuery Scriptaculous Comet Filesystem) ];
		project: 'Seaside3-Development' copyFrom: 'Seaside3' with: [ spec loads: #(Core Zinc JSON REST Email Javascript JQuery Scriptaculous Comet Filesystem Development) ].

**Comment by jbrichau** [comment]
Ha, that explains.
No, version 3.4.4 is the latest one. See https://github.com/SeasideSt/Seaside/releases

Pharo 9 is only supported from 3.4.4 onwards.

**Comment by jbrichau** [comment]
@tblanchard Hi Todd, I think we can close this one?

**Comment by tblanchard** [comment]
Yes, all good now.
