### ISSUE TITLE
Implement CORS request filter

### ISSUE THREAD

**Issue by eMaringolo** [SeasideSt/Seaside#1270]
I'm creating this issue as a placeholder, since I have a `WACORSFilter` that I plan to submit back to this repository soon.

I'm polishing it to make it more user friendly (beyond my basic needs) and I added a functional test to make it work (it involves setting up an adapter on another port to actually need CORS handling.

As such, the filter is meant to be used on any request handler (app, session, rest), although it would certainly make more sense in REST contexts.

**Comment by jbrichau** [comment]
This one got merged last year :-)
