### ISSUE TITLE
v3.4.5 Seaside-Core.package/GRPlatform.extension/instance/seasideVersion.st shows 3.4.4

### ISSUE THREAD

**Issue by rjsargent** [SeasideSt/Seaside#1275]
Related to issue #1143, v3.2.5 Seaside-Core.package/GRPlatform.extension/instance/seasideVersion.st shows 3.2.2.

I suggest publishing an updated version of this method immediately after tagging the released version, so it won't be forgotten later when deciding to prepare a release.

**Comment by jbrichau** [comment]
Argh. It's embarrassing how many times I forget that. Fixed it for 3.4.5 and already updated the method for 3.4.6 now. Not sure if changing the moment to change the method is going to fix this for the future but doing an automated check is also rather hard.
