### ISSUE TITLE
Pharo 9.0 Load script fails with exception (conflict with Great visions).

### ISSUE THREAD

**Issue by Robert-Briggs** [SeasideSt/Seaside#1276]
Executed the load scrip provided in Playground.

Stops part way through with the following exception.

"MetacelloConflictingProjectError: Load Conflict between existing BaselineOfGrease [baseline] from github://SeasideSt/Grease:v1.5.x/repository and BaselineOfGrease [baseline] from github://SeasideSt/Grease:v1.7.x/repository"
See screenshot.

<img width="1562" alt="Screenshot 2021-08-19 at 09 56 46" src="https://user-images.githubusercontent.com/69461242/130040073-2ebfa578-5c72-4c04-80a6-0ce9cd1ee2c3.png">

**Comment by jbrichau** [comment]
Hi,

This load conflict pops up because you already have a previous version of Grease loaded in your image. In case of Metacello conflicts, you need to handle these yourself. See https://github.com/Metacello/metacello/blob/master/docs/MetacelloUserGuide.md for more info on Metacello.

In this case, it is perfectly safe (and actually necessary) to upgrade Grease to latest 1.7.x because Seaside requires this version of Grease.

**Comment by Robert-Briggs** [comment]
Unable to work out what to do from the Metacello user guide.  It seems to be that the Grease:v1.5.x/repository is not locked.  Therefore the 'useIncoming' behaviour is bypassed and the exception raised.  Please advise.

**Comment by Robert-Briggs** [comment]
PS.  I've raised this issue to against the Grease repository in GitHub as it presumably needs to be resolved in GitHub rather than my image, unless you can advise me how to safely remove existing Grease installation in my image.

**Comment by jbrichau** [comment]
You should add `onConflictUseIncoming: #('Grease')` or just plain `onConflictUseIncoming`. See https://github.com/Metacello/metacello/blob/master/docs/MetacelloUserGuide.md#conflicts

Github issues are not the recommended way to get help. May I recommend joining the Pharo mailinglist or the Discord server: https://pharo.org/community.html

**Comment by Robert-Briggs** [comment]
OK

 

I’ll try.

 

Thanks for your help.  I do think however this conflict should be handled automatically by accounting for the conflict – perhaps offering the user the option to retain or update the existing version of a dependent package rather than just halting the load.

 

I am already on the Pharo mailing list and have used the Discord Server.

 

Regards

Bob.

 

You should add onConflictUseIncoming: #('Grease') or just plain onConflictUseIncoming. See https://github.com/Metacello/metacello/blob/master/docs/MetacelloUserGuide.md#conflicts

Github issues are not the recommended way to get help. May I recommend joining the Pharo mailinglist or the Discord server: https://pharo.org/community.html

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jbrichau** [comment]
@Robert-Briggs This is how Metacello works, not something Seaside can control.
