### ISSUE TITLE
WAPharoWalkback Internal Error Context dNU #namedTempAt:

### ISSUE THREAD

**Issue by johnhwoods** [SeasideSt/Seaside#1307]
WAPharoWalkback displays "Internal Error" on Pharo 10

This is because the variable listing method refers to `Context>>tempNamedAt:`
 which was deprecated in 9.0 and has gone in 10.0

**Comment by johnhwoods** [comment]
To replicate: 

Start a fresh P10.  Install Seaside thusly:
```Smalltalk
Metacello new
 baseline:'Seaside3';
 repository: 'github://SeasideSt/Seaside:master/repository';
 load
 ``` Then create a component with a basic mistake in rendering:
 ```Smalltalk
 renderContentOn: html
	html text; with: 'hello'
```

**Comment by jbrichau** [comment]
Thanks. This is now fixed in https://github.com/SeasideSt/Seaside/commit/722c2cc9cc4973e29f18ccdf6dcf2f666b0bd2ca
