### ISSUE TITLE
WAScreenshot is broken

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Seaside#1333]
WAScreenshot is broken in Pharo. At least with Pharo 10 on macOs:

- the screenshot is empty
- `WAScreenshot >> #handleEvent:` references `Sensor` which is undeclared, it used to be an instance of `EventSenor`
- `WAScreenshot >> #handleEvent:` sends `#handleEvent:` or `#processEvent:`, neither of which seem implement or working with the array created in `WAScreenshot >> click:`

**Comment by jbrichau** [comment]
Was fixed in https://github.com/SeasideSt/Seaside/pull/1335
