### ISSUE TITLE
Control panel broken in Pharo 11 due to Spec2 change

### ISSUE THREAD

**Issue by astares** [SeasideSt/Seaside#1345]
![image](https://user-images.githubusercontent.com/5980033/192768642-86c562f9-ba8a-42a0-b4e0-691a560a9003.png)

Easy but *bad* workaround: change #asToolbarPresenter into #asMenuBarPresenter

will give you:

![image](https://user-images.githubusercontent.com/5980033/192769557-4ce6383e-11b4-4531-80a3-5a41160dbdae.png)

**Comment by astares** [comment]
Correct way to fix this is to have the missing method implemented in Spec2:

```Smalltalk
asToolbarPresenter
	^ SpToolbarPresenterBuilder new
		visit: self;
		toolbarPresenter
```

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/192771743-e42fa998-77c9-472f-83dd-4fe73006b236.png)

**Comment by astares** [comment]
Opened an issue for Spec2:  https://github.com/pharo-spec/Spec/issues/1316

**Comment by svenvc** [comment]
> Correct way to fix this is to have the missing method implemented in Spec2:
> 
> ```smalltalk
> asToolbarPresenter
> 	^ SpToolbarPresenterBuilder new
> 		visit: self;
> 		toolbarPresenter
> ```

I can confirm that this works fine !
