### ISSUE TITLE
Cannot load from BaselineOf, error Character did not understand #greaseInteger

### ISSUE THREAD

**Issue by labordep** [SeasideSt/Seaside#1347]
To reproduce : 
1- Create a new Pharo 11 image
My config : Pharo-11.0.0+build.392
OS : Windows 11 Pro 64 bits

2 - Load Seaside by executing this script : 
```
Metacello new
 baseline:'Seaside3';
 repository: 'github://SeasideSt/Seaside:master/repository';
 load
```
![image](https://user-images.githubusercontent.com/49183340/209442800-5254b4aa-7006-4060-892c-e161ae50a801.png)

3 - There is a warning about dependencies, :
![image](https://user-images.githubusercontent.com/49183340/209442836-7ec10c17-a1ad-4b45-bbd6-3cbb7b6e2720.png)
I don't know what to do here, so I ignore it and play with "Proceed" button.

4 - Error signal : 
![image](https://user-images.githubusercontent.com/49183340/209442877-1451fc01-c95f-4cc9-91ae-62a1d4a81058.png)

Thanks for your help :-)

**Comment by theseion** [comment]
We don't support Pharo 11 yet. The baseline is missing the definitions for Pharo 11. You can add them yourself and loading will work (simply add the Pharo 11 equivalent where it says `pharo10...` in the baseline), but be aware that it is very likely that some things will not work.

**Comment by labordep** [comment]
Ok thanks, I will test :)
