### ISSUE TITLE
Suggested Extension for WASelectTag

### ISSUE THREAD

**Issue by JoachimTuchel** [SeasideSt/Seaside#1352]
Hi there,

sorry for not providing a pull request. I have no idea how to do that from VAST (maybe a case of ignorance, not sure)...

I had to add some attributes to options in a select tag in order to acces them from javascript. So I added an inst var to `WASelectTag` named `itemConfigBlock` together with a getter and setter.

Then I modified `WASelectTag>>renderListItem:labelled:` to

    renderListItem: anObject labelled: aString
	    | option |
	    option := canvas option.
	    self hasCallback
		    ifTrue: [ option value: (self valueFor: anObject) ].
	    titleBlock isNil
		    ifFalse: [ option title: (self titleFor: anObject) ].
		
	    "Addition by Joachim Tuchel: configure each option with a block (if provided), like add an attribute etc."
	    itemConfigBlock ifNotNil: [:block | block value: option value: anObject].	
		
	    option
		selected: (self isSelected: anObject);
		disabled: (self isEnabled: anObject) not;
		with: aString

Maybe naming the variable differently, like `configureOptionsWith` or such would make the code even nicer.

With this, I can provide a block to the select tag that  modifies its option tag. Like this:

     html select
       ...
       itemConfigBlock: [:listItem :object | listItem attributeAt: 'data-modify' put: object id asString];

This will modify the option tag to read something like `<option data-modify="42" ...>This option</option>`

Maybe others find this useful and you consider adding this to seaside. I found it very helpful for my case of hiding/showing elements based on the current selection or displaying help text for the selected item.

Joachim

**Comment by jbrichau** [comment]
Hi @JoachimTuchel ,

To have fine-grained control on the rendered options inside of a `select`, the `WASelectTag` offers the possibility to explicitly render the options inside the `with:` block passed to the select tag. You can find examples in the 'Seaside functional tests', implemented in `renderSingleSelectionCustomOn:` and `renderNestedSelectionOn:`. 

If that solution does not work well for you, let me know what issues you encounter.

**Comment by JoachimTuchel** [comment]
Will take a look, thanks fopr the pointer!

**Comment by JoachimTuchel** [comment]
Thanks for looking into this. Your suggestion wirks perfectly.
