### ISSUE TITLE
Squeak needs variant implementation of #openDebuggerOn:

### ISSUE THREAD

**Issue by timrowledge** [SeasideSt/Seaside#1390]
The vanilla Process>>#debug:title:full: is deprecated in Squeak 6.1.

I propose implementing GRSqueakPlatform>>#openDebuggerOn:
openDebuggerOn: anError
	"Squeak variant based on the Pharo platform code, intended to avoid the deprecated #debug:title:full: message"

	| process |
	process := Processor activeProcess.
	"If we are running in the UI process, we don't want to suspend the active process. The
	error was presumably triggered while stepping in the Debugger. If we simply immediately
	signal an UnhandledError, the debugger will catch this and display the signaling context.
	It isn't perfect or pretty but it works."
	process == Project uiProcess
		ifTrue: [UnhandledError signalForException: anError ]
		ifFalse: 
			[WorldState addDeferredUIMessage:
				[ToolSet handleError: anError].
			process suspend]

**Comment by timrowledge** [comment]
Better, simpler, more resilient version - 
[Grease-Squeak-debugger.2.txt](https://github.com/SeasideSt/Seaside/files/13302664/Grease-Squeak-debugger.2.txt)

**Comment by marschall** [comment]
Thanks, will be resolved in https://github.com/SeasideSt/Grease/pull/181.

**Comment by timrowledge** [comment]
Many thanks for taking the time to do this.

> On 2024-07-16, at 12:29 PM, Philippe Marschall ***@***.***> wrote:
> 
> 
> Thanks, will be resolved in SeasideSt/Grease#181.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
> 


tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
Earth is 98% full...please delete anyone you can.
