### ISSUE TITLE
Squeak WAWebServerAdaptor>>#responseFrom: sends #oldNetscapeString

### ISSUE THREAD

**Issue by timrowledge** [SeasideSt/Seaside#1392]
WAWebServerAdaptor>>#responseFrom: fails when it sends #oldNetscapeString. I found some issues relating to this and commented but damned if I can find them now to add this info to.

So, replace #oldNetscapeString with #rfc6265String and all seems ok, at least to a not very knowledgeable about this stuff hacker.

[WAWebServerAdaptor.txt](https://github.com/SeasideSt/Seaside/files/13302777/WAWebServerAdaptor.txt)

**Comment by marschall** [comment]
`WAWebServerAdaptor` is part of `WebClient-Seaside-Adaptor` which is maintained here https://ss3.gemtalksystems.com/ss/WebClient.html so I'm inclined to close.

**Comment by timrowledge** [comment]
Thanks for looking at this. So you suggest closing the seaside issue in favour of solving it in the WebClient package on ss3? OK I guess, assuming keeping things on a very old and not exactly active repository is wise. 

At least in the case of the WebClient/WebHost stuff it is all in the trunk Squeak image, which also makes it harder for people to remember to track outside packages. Is the WebX stuff used by Pharo? I had an idea they had moved to using Zinc - in which case maybe the related seaside packages ought to be moved into some Seaside-Squeak-X package?

**Comment by marschall** [comment]
> So you suggest closing the seaside issue in favour of solving it in the WebClient package on ss3?

Yes.

> OK I guess, assuming keeping things on a very old and not exactly active repository is wise.
>
> At least in the case of the WebClient/WebHost stuff it is all in the trunk Squeak image, which also makes it harder for people to remember to track outside packages.

I don't know where WebClient is maintained. We currently load `WebClient-Seaside-Adaptor` from ss3. If somebody wants to take over the maintenance of `WebClient-Seaside-Adaptor` it could be moved somewhere else, even here.

> Is the WebX stuff used by Pharo? 

Not to my knowledge.

> I had an idea they had moved to using Zinc - in which case maybe the related seaside packages ought to be moved into some Seaside-Squeak-X package?

It's already in `WebClient-Seaside-Adaptor`, since only Squeak uses WebClient there is no need for portability.
