### ISSUE TITLE
JQGoogleLibrary to update to 3.7.1

### ISSUE THREAD

**Issue by sanjayminni** [SeasideSt/Seaside#1408]
JQGoogleLibrary still points to 3.6.0 - to update to 3.7.1
```
>>updateRoot: anHtmlRoot
...
anHtmlRoot javascript url: 'https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js'
```

**Comment by jbrichau** [comment]
Thanks for reporting!
Fixed in https://github.com/SeasideSt/Seaside/commit/2b55f20edfa40a5fea307cb003c89a1db4bac1f5
