### ISSUE TITLE
Version 3.5.6 loading error because of Grease dep

### ISSUE THREAD

**Issue by vitormcruz** [SeasideSt/Seaside#1411]
Version 3.5.6 seems to requires Grease 1.17.x, but there is no such tag, so installing Seaside in this version renders an error:
[Pharo 11, Windows 10]

```Metacello new
 baseline:'Seaside3';
 repository: 'github://SeasideSt/Seaside:v3.5.6/repository';
 load
```

![image](https://github.com/SeasideSt/Seaside/assets/1001427/79dc2e1b-1662-40d2-9b93-f03f647318ad)

**Comment by jbrichau** [comment]
It’s github://SeasideSt/Grease:v1.17.x/repository and the tag exists: https://github.com/SeasideSt/Grease/releases/tag/v1.17.x

Not sure why you get that error…

**Comment by vitormcruz** [comment]
Deleting my clone of grease and letting inceberg to clone it again solved the problem. I have seen this happend before, but I don't know why... I will close the issue.
