### ISSUE TITLE
Deprecated messages in functional tests

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Seaside#1418]
When running the functional tests several deprecated messages are sent:

- `WARenderLoopContinuation>>#updateRoot:` sends `#charset:` to `WAMetaElement`
- `WACanvasTableFunctionalTest` sends
  - `WATableDateTag>>#scope:`
  - `WATableCellTag>>#align:`
  - `WATableCellTag>>#character:`
- `WAHtml5ElementsTest` sends `WAHtmlCanvas>>#menu`
- `WALotsaLinksFunctionalTest` sends `WAAnchorTag>>name:`
- `WAPerformanceFunctionalTest` sends `WAHtmlCanvas>>#big` and `WAAnchorTag>>#name:`
- `WAPhraseElementsFunctionalTest` sends `WAHtmlCanvas>>#acronym`
- `WASelectionDateTableFunctionalTest` sends `WATableCellTag>>#align:`

**Comment by jbrichau** [comment]
Just to note: the intention was to adapt the tests when the deprecated messages are actually removed.

**Comment by jbrichau** [comment]
The `WAMetaElement>>#charSet:` deprecation was not correct. The `charSet` attribute is deprecated on `<a/>` and `<script/>` tags only. I will remove it.
