### ISSUE TITLE
Implementations of #asJson in Seaside and GToolkit conflict

### ISSUE THREAD

**Issue by Rinzwind** [SeasideSt/Seaside#1433]
There are conflicting implementations of `#asJson` in Seaside and Glamorous Toolkit. Using Glamorous Toolkit v1.0.975, the test in the following fails:

```smalltalk
Metacello new
	baseline: 'Seaside3';
	repository: 'github://SeasideSt/Seaside:d90609cfd7005f52/repository';
	load: 'Tests'.
(Smalltalk at: #WAJsonStreamTest) debug: #testArray
```

This is because `#asJson` doesn’t answer a String but a GtJson:

```smalltalk
#(1 2 3) asJson "=> a GtJson(root)"
```

<p align="center">
<img width="686" src="https://github.com/user-attachments/assets/4173ca7d-6464-4a16-89ee-1ad28cc104fc">
</p>

**Comment by marschall** [comment]
Interesting. Does GT also define `#jsonOn:`?

**Comment by Rinzwind** [comment]
There are no implementors of `#jsonOn:` in Glamorous Toolkit v1.0.975.

To get a String with JSON from a GtJson, it can be sent `#asJsonString`. The classes implementing `#asJsonString` are GtJsonBasic, GtJsonModel and YAMLParseNode, so sending the message to an Array causes a MessageNotUnderstood to be signaled, leaving a rename of Seaside’s `#asJson` to `#asJsonString` as one option to avoid the conflict.

**Comment by Rinzwind** [comment]
GToolkit’s `#asJson` has been deprecated in [GToolkit issue #3895](https://github.com/feenkcom/gtoolkit/issues/3895).

**Comment by Rinzwind** [comment]
I’ll close this. As noted [in GToolkit issue #3895](https://github.com/feenkcom/gtoolkit/issues/3895#issuecomment-2228849862), the conflict remains as long as the deprecated methods remain in GToolkit. The workaround is to just remove them, see commit c0e63ad95c84ae45.
