### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by bmason** [SeasideSt/Seaside#1440]
new install of Pharo 12 under windows 11

Metacello new
 baseline:'Seaside3';
 repository: 'github://SeasideSt/Seaside:master/repository';
 load

aborting
I got an error while cloning: There was an authentication error while trying to execute the operation: . 
This happens usually because you didn't provide a valid set of credentials. 
You may fix this problem in different ways: 

1. adding your keys to ssh-agent, executing ssh-add ~/.ssh/id_rsa in your command line.
2. adding your keys in settings (open settings browser search for "Use custom SSH keys" and
add your public and private keys).
3. using HTTPS instead SSH (Just use an url in the form HTTPS://etc.git). I will try to clone the HTTPS variant.

**Comment by Rinzwind** [comment]
If you got a debugger window when trying the loading snippet, could you post the error as it appears in the debugger?

The strings ‘I got an error while cloning’ and ‘I will try to clone the HTTPS variant’ are, as far as I can tell, only used in [`#createIcebergRepositoryWithFallbackFor:url:` on MCGitBasedNetworkRepository](https://github.com/pharo-vcs/iceberg/blob/28c5d2e49ba8455ce93447a9de2951c50d1878fc/Iceberg/MCGitBasedNetworkRepository.extension.st#L26-L35) to log that an IceAuthenticationError was handled by a fallback to the HTTPS URL. That doesn’t imply that loading failed, it’s just a warning.

If you didn’t get a debugger window, there was presumably no unrecoverable error, and you should be able to open the Seaside welcome page at ‘[http://localhost:8080](http://localhost:8080)’.

**Comment by Rinzwind** [comment]
@bmason: I’m closing this on the assumption that my previous comment resolved the issue, but please do leave another comment if that’s not the case.
