### ISSUE TITLE
Depricate WARenderContext >> #callbackAt:

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SeasideSt/Seaside#615]
```
WARenderContext >> #callbackAt: is unused, if there are not good reasons to 
keep it, it should be removed.
```

Original issue reported on code.google.com by `philippe...@gmail.com` on 1 Dec 2010 at 6:48

**Comment by marschall** [comment]
Name: Seaside-Core-pmm.864
Author: pmm
Time: 17 July 2015, 11:52:05.680548 am
UUID: c126e127-453b-48a8-a3e1-ccb29c7a2c53
Ancestors: Seaside-Core-pmm.863

#615 Depricate WARenderContext >> #callbackAt:
