### ISSUE TITLE
WAResonse >> #location: should not do string conversion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SeasideSt/Seaside#773]
```
string conversion should happen in the server adapter #responseFrom: this would 
also help buffer usage.
```

Original issue reported on code.google.com by `philippe...@gmail.com` on 23 Dec 2013 at 7:17

**Comment by marschall** [comment]
This is a requirement for #872

**Comment by marschall** [comment]
Name: Seaside-Core-pmm.872
Author: pmm
Time: 22 August 2016, 10:05:29.42472 am
UUID: 1cdf5e52-2b10-4e53-a340-3eb3187cb1f7
Ancestors: Seaside-Core-pmm.871

WAResonse >> #location: should not do string conversion #773
- https://github.com/SeasideSt/Seaside/issues/773

Name: Seaside-Tests-Core-pmm.310
Author: pmm
Time: 22 August 2016, 10:07:21.002147 am
UUID: 1408ba8e-87a7-4ffb-a339-6cb422301c62
Ancestors: Seaside-Tests-Core-pmm.309

WAResonse >> #location: should not do string conversion #773
- https://github.com/SeasideSt/Seaside/issues/773

Name: Seaside-Tests-Security-pmm.6
Author: pmm
Time: 22 August 2016, 10:08:04.642211 am
UUID: 9bb18da8-25f9-406d-a588-57886706c00b
Ancestors: Seaside-Tests-Security-pmm.5

WAResonse >> #location: should not do string conversion #773
- https://github.com/SeasideSt/Seaside/issues/773

Name: Seaside-Tests-Session-pmm.82
Author: pmm
Time: 22 August 2016, 10:08:49.002097 am
UUID: 9bd908e2-ee6a-45ed-8756-1b0c2b28f29f
Ancestors: Seaside-Tests-Session-pmm.81

WAResonse >> #location: should not do string conversion #773
- https://github.com/SeasideSt/Seaside/issues/773
