### ISSUE TITLE
No able to view / compile Pharo 3 / Pharo 4 code in Seaside (3.1)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SeasideSt/Seaside#837]
```
What steps will reproduce the problem?
1. Try to edit code in Halos and then save

What is the expected output? What do you see instead?

in Pharo 3.0 I get an error
   MessageNotUnderstood: receiver of "generateWithSource" is nil
   Your request could not be completed. An exception occurred.

in 4.0 I cannot see the code only to allow me to edit
incidentally when trying to install seaside in Pharo 4.0 I get the exception / 
error
  This package depends on the following classes: 
    ContextPart 
  You must resolve these dependencies before you will be able to load these
   definitions: 
    localAt: 
    localAt:put: 
    localSize 
    serialiseOn: 
  Select Proceed to continue, or close this window to cancel the operation.   

Please provide any additional information below.

I am using Windows 7

```

Original issue reported on code.google.com by `sanjay.m...@gmail.com` on 12 Dec 2014 at 5:56

**Comment by marschall** [comment]
Name: Seaside-Pharo-Development-pmm.92
Author: pmm
Time: 17 July 2015, 11:25:20.105376 am
UUID: 431424dd-39bf-494e-9c45-4ead83739a8b
Ancestors: Seaside-Pharo-Development-pmm.91

#837 No able to view / compile Pharo 3 / Pharo 4 code in Seaside (3.1)
- fix MNU when editing a method without selecting a protocol first
- source still lost in Pharo 4

**Comment by marschall** [comment]
Name: Seaside-Pharo-Development-pmm.94
Author: pmm
Time: 17 July 2015, 11:44:38.522805 am
UUID: 1ff7ea9a-2904-4ae5-89e1-91b8413bf5eb
Ancestors: Seaside-Pharo-Development-pmm.93

#837 No able to view / compile Pharo 3 / Pharo 4 code in Seaside (3.1)
- source no longer lost in Pharo 4
