### ISSUE TITLE
Seaside Rest failure in Pharo4

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Seaside#840]
Reported by gareth@inspired.org:
```
Hi

I'm having a reoccurance of an error I had that was fixed in Seaside 3.1.3.
Fresh Pharo4, load, load Rest, create handler, create method, register, and its not found.
Complete code to recreate below:

|aClass|
Gofer new
    url:'http://www.smalltalkhub.com/mc/Seaside/MetacelloConfigurations/main';
    package: 'ConfigurationOfSeaside3';
    load.

((#ConfigurationOfSeaside3 asClass) project latestVersion) load; load: #('REST').

aClass := ((#WARestfulHandler asClass) subclass: #WATestRestAPI
    instanceVariableNames: ''
    classVariableNames: ''
    category: 'Seaside-Test-REST').
    
aClass compile: 'get 
<get>
self requestContext
        respond: [:t1 | 
            t1 contentType: ''text/plain''.
            t1 nextPutAll: ''test'']'.
(#WAAdmin asClass) register: aClass at: 'testapi'.

(((#ZnZincServerAdaptor asClass) manager: (#WAServerManager asClass) default) port: 4000) start.

self assert: (ZnEasy get: 'http://localhost:4000/testapi') isNotFound not
```

**Comment by jbrichau** [comment]
It seems the addition in the commit below breaks the creation of <get> methods with zero arguments. The path gets initialized with the method selector and thus always has a length of 1. There are no 0 length paths, so this seems broken since 3 years..???

@marschall do you remember what the intent was for this change?

```
Name: Seaside-REST-Core-pmm.48
Author: pmm
Time: 24 August 2012, 4:22:37 pm
UUID: 7c575e6c-04b6-4a29-b0d8-f59f8cae63af
Ancestors: Seaside-REST-Core-pmm.47

- <path: > defaults to method name
```

**Comment by jbrichau** [comment]
I think the path initialization should be:

```
	(GRPlatform current argumentNamesOf: aCompiledMethod) isEmpty
		ifTrue:[ path := nil ]
		ifFalse:[ path := aCompiledMethod selector greaseString ].
```

**Comment by marschall** [comment]
I assume it was so that you could do
```smalltalk
testapi
  <get>
```
And it would map to `/testapi`

**Comment by riverdusty** [comment]
FYI: This was the issue I had last time.
http://forum.world.st/REST-in-Seaside-3-in-Pharo-3-td4774432.html

**Comment by jbrichau** [comment]
@riverdusty 

So, as @marschall mentions, this is not a bug but a feature. 
As you noticed, an undocumented feature that breaks current documentation though...

To achieve what you want, you need to add a #path: pragma to the method implementation as shown below.

```
get 
<get>
<path: ''>

self requestContext
        respond: [:t1 | 
            t1 contentType: 'text/plain'.
            t1 nextPutAll: 'test']
```
Otherwise, the method selector defines the path for the handler, which means your implementation would map to the url ```/testapi/get```

I'll close this issue but I'll open another one mentioning we need to update documentation.
