### ISSUE TITLE
REST documentation needs updating

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Seaside#841]
It seems some changes in 3.1 Rest were not updated in the documentation. For example, issue #840 was confusing because according to the Seaside book, this should work (e.g. http://book.seaside.st/book/advanced/restful/getting-started/define-service)

**Comment by riverdusty** [comment]
How can I help?
I just discovered for custom paths I have to:
```
test: thing on: otherthing
    <get>
    <path: '/test/{thing}/{otherthing}'>
...
```

**Comment by jbrichau** [comment]
You are helping already, by adding to the issue.
It would be great if people who went through the entire doc, annotated all errors in this issue tracker, so we can pick it up.

I would not edit to the existing book at this time, because it's on an old Pier image and I am looking at moving both the website and the book to a new one.

**Comment by marschall** [comment]
Done
