### ISSUE TITLE
subStrings: is deprecated in Pharo 5

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Seaside#844]
subStrings: is deprecated in Pharo 5, they recommend #substrings:
-> the usual, check all platforms and Pharo versions, check all senders, write transformation rule or add it to Grease

**Comment by Uko** [comment]
`substrings:` is present in pharo 3 and 4, not present in squeak. Can anyone check gemstone?

**Comment by dalehenrich** [comment]
`substrings:` is not present in GemStone, we have `substrings` and `subStrings`, so `subStrings:` is a new one ... I suppose I could add `substrings:` to the base or it could be done via Grease ... I prefer that it be added to Grease, since that will ensure that the new method gets included for Seaside ...

**Comment by jbrichau** [comment]
@dalehenrich `subStrings:` is in the Squeak package on CharacterCollection in GemStone. There is a Grease test for it, so it should work fine. I suppose we can add `substrings:` to Grease as an alias for `subStrings:`, but would it not make sense to add it to the Squeak package (or maybe a Pharo package) just like what we did for when `includesSubstring:` was renamed to `includesSubString:` in Pharo 3?

The method comment in Grease mentions that `subStrings:` is ANSI, btw.

**Comment by dalehenrich** [comment]
@jbrichau either way works fine ... Grease is part of the "GsDevKit_home base" so either way the method will show up in the standard image .... I don't think the Pharo package is loaded by default, so it would be an extra dependency for Seaside if we put it there (Seaside32 doesn't currently depend upon the pharo compat package). The squeak package is pretty fragmented right now so it would mean adding it to each of the different packages ... certainly doable, but a wrapper in Grease would be the simplest:) 

If it is ANSI it might just show up in 3.2.16 and 3.3.2 "on it's own" and I'll find out on Tuesday or later this week ...

**Comment by marschall** [comment]
For portability I removed all of your `#subStrings:` and `#substrings:` senders and directed them to a class side method in GRPlatform. This method is optimised for our use cases and in these cases allocates a lot less.

The only senders left are tests for ANSI and `#subStrings:` is in ANSI 5.7.10 so I'll leave those in.

Name: Seaside-Core-pmm.871
Author: pmm
Time: 21 August 2016, 4:51:52.955655 pm
UUID: e48bbc7c-53e4-4d79-80f9-fc755db59a6b
Ancestors: Seaside-Core-pmm.870

subStrings: is deprecated in Pharo 5 #844
- https://github.com/SeasideSt/Seaside/issues/844
- remove all senders

Name: Seaside-Tests-Core-pmm.309
Author: pmm
Time: 21 August 2016, 4:54:21.368489 pm
UUID: 259298aa-2c00-4edf-8bbd-626ab6e3b42c
Ancestors: Seaside-Tests-Core-pmm.308

subStrings: is deprecated in Pharo 5 #844
- https://github.com/SeasideSt/Seaside/issues/844
- remove all senders

subStrings: is deprecated in Pharo 5 #844
- https://github.com/SeasideSt/Seaside/issues/844
- remove all senders

Name: Seaside-REST-Core-pmm.64
Author: pmm
Time: 21 August 2016, 4:55:19.613716 pm
UUID: 043ce631-d821-4067-9af5-12510748a948
Ancestors: Seaside-REST-Core-pmm.63

subStrings: is deprecated in Pharo 5 #844
- https://github.com/SeasideSt/Seaside/issues/844
- remove all senders

Name: Seaside-Tools-Core-pmm.28
Author: pmm
Time: 21 August 2016, 4:57:48.845308 pm
UUID: 908c03b1-e32b-4621-a750-50dd5871326c
Ancestors: Seaside-Tools-Core-JohanBrichau.27

subStrings: is deprecated in Pharo 5 #844
- https://github.com/SeasideSt/Seaside/issues/844
- remove all senders

Name: Scriptaculous-Components-pmm.117
Author: pmm
Time: 21 August 2016, 4:59:09.581069 pm
UUID: 43688765-ebb5-41d1-a732-8fdecd71d437
Ancestors: Scriptaculous-Components-JohanBrichau.116

subStrings: is deprecated in Pharo 5 #844
- https://github.com/SeasideSt/Seaside/issues/844
- remove all senders

Name: Scriptaculous-Core-pmm.107
Author: pmm
Time: 21 August 2016, 5:00:55.268302 pm
UUID: 48cf7403-6a57-4ac9-8b4b-deb2eda5a7b8
Ancestors: Scriptaculous-Core-JohanBrichau.106

subStrings: is deprecated in Pharo 5 #844
- https://github.com/SeasideSt/Seaside/issues/844
- remove all senders

Name: Seaside-Pharo-Email-pmm.20
Author: pmm
Time: 21 August 2016, 5:01:34.284002 pm
UUID: 623f477d-4c3d-4b9c-8f27-12ed2568fc19
Ancestors: Seaside-Pharo-Email-JohanBrichau.19

subStrings: is deprecated in Pharo 5 #844
- https://github.com/SeasideSt/Seaside/issues/844
- remove all senders

Name: JQuery-UI-pmm.95
Author: pmm
Time: 21 August 2016, 5:02:33.153003 pm
UUID: 3b1210c0-1d99-41bc-bfc4-8ce1ffd8f49f
Ancestors: JQuery-UI-JohanBrichau.94

subStrings: is deprecated in Pharo 5 #844
- https://github.com/SeasideSt/Seaside/issues/844
- remove all senders
