### ISSUE TITLE
Seaside-Security not included in Travis tests

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Seaside#853]
Because the tests for the Cryptography package are being run as well (and fail), we get a failed build. Therefore, I removed the Security package from the `Tests` group.

In the end, we want these back in as they are now only covered by the Pharo CI server builds (and not in Travis).

**Comment by dalehenrich** [comment]
Ah .. very good idea ...

**Comment by marschall** [comment]
I excluded the Cryptography tests and added the security package to the test group.
