### ISSUE TITLE
Seaside Rest PATCH support

### ISSUE THREAD

**Issue by riverdusty** [SeasideSt/Seaside#854]
Proposed (accepted?) standard: http://tools.ietf.org/html/rfc5789
In seaside-REST-Core changes need to be made to WARoute class and WARouteBuilder.

```
!WARoute class methodsFor: 'instance creation' stamp: 'dusty 9/2/2015 17:30'!
patch: aSymbol
	^ WASimpleRoute method: 'PATCH' selector: aSymbol! !
```
```
!WARoute class methodsFor: 'instance creation' stamp: 'dusty 9/2/2015 17:30'!
patch: aString selector: aSymbol
	^ WAComplexRoute
		method: 'PATCH'
		selector: aSymbol
		pattern: aString! !
```
```
!WARouteBuilder methodsFor: 'configuration methods' stamp: 'dusty 9/3/2015 09:28'!
patch
	<configuration>
	
	self method: 'PATCH'! !
```

Changes will also have to be made to ZnClient and ZnRequest, link here: https://pharo.fogbugz.com/f/cases/edit/16469/Zinc-support-for-PATCH

**Comment by marschall** [comment]
Name: Seaside-REST-Core-pmm.61
Author: pmm
Time: 18 August 2016, 12:53:16.178228 pm
UUID: 85799618-61ad-4557-bcd5-6ce4ba6e4734
Ancestors: Seaside-REST-Core-JohanBrichau.60

Seaside Rest PATCH support #854
https://github.com/SeasideSt/Seaside/issues/854

Name: Seaside-Tests-REST-Core-pmm.34
Author: pmm
Time: 18 August 2016, 12:53:49.720703 pm
UUID: 48595527-0109-4298-a2d0-2ae1f40f1202
Ancestors: Seaside-Tests-REST-Core-jok.33

Seaside Rest PATCH support #854
https://github.com/SeasideSt/Seaside/issues/854
