### ISSUE TITLE
MessageSend overrides in Squeak 5

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Seaside#858]
Hi, today I noticed I had a dirty Kernel package in Squeak 5 due to
Grease overrides of three methods.  Squeak has subsequently made
improvements to these methods which may be able to be adopted by
Pharo.  They were changed in 2011 to not create a temporary Array.

   MessageSend>>#value:
   MessageSend>>#value:value:
   MessageSend>>#valueWithPossibleArgs:

All the Grease, JQuery, Javascript and Seaside tests passed with the
modern versions.  The Squeak 5 version of these methods is in the
attached changeset.

Best,
  Chris

http://lists.squeakfoundation.org/pipermail/seaside-dev/2015-October/006682.html

**Comment by jbrichau** [comment]
This issue was moved to SeasideSt/Grease#12
