### ISSUE TITLE
JQAjaxSetup>>timeout: overrides JSObject>>timeout: with unrelated different behavior

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Seaside#861]
Wrapping an Ajax request with the JSTimeout function is therefore not possible using the timeout: function.

**Comment by marschall** [comment]
Why would you want to request an AJAX request with a timeout function?
What do you propose as a solution? Maybe we should rename to JSObject>>setTimeout: ?

**Comment by jbrichau** [comment]
We ran into this when implementing server polling from the client: a request is fired after some time only to check on the completion of long-running tasks. 

The best thing to do would be to deprecate the JSObject method and implement setTimeout: as a replacement. Good suggestion.

**Comment by marschall** [comment]
Do we want to do this directly or fist deprecate it?

**Comment by jbrichau** [comment]
`timeout:` is a commonly used method, so to ease porting it's better to deprecate it first.

**Comment by marschall** [comment]
Name: Javascript-Core-pmm.100
Author: pmm
Time: 22 August 2016, 11:16:28.426936 am
UUID: e0a0df0a-3119-4bb1-9e40-01c6c91d0b83
Ancestors: Javascript-Core-pmm.99

JQAjaxSetup>>timeout: overrides JSObject>>timeout: with unrelated different behavior #861
- https://github.com/SeasideSt/Seaside/issues/861

Name: Javascript-Tests-Core-pmm.74
Author: pmm
Time: 22 August 2016, 11:17:00.883132 am
UUID: 1cf412fc-9a6b-4854-89e5-8ad498c00bf6
Ancestors: Javascript-Tests-Core-JohanBrichau.73

JQAjaxSetup>>timeout: overrides JSObject>>timeout: with unrelated different behavior #861
- https://github.com/SeasideSt/Seaside/issues/861

Name: Scriptaculous-Tests-Components-pmm.45
Author: pmm
Time: 22 August 2016, 11:17:28.371855 am
UUID: b317cd44-ad1f-4014-a6d6-d17b02a6d94d
Ancestors: Scriptaculous-Tests-Components-JohanBrichau.44

JQAjaxSetup>>timeout: overrides JSObject>>timeout: with unrelated different behavior #861
- https://github.com/SeasideSt/Seaside/issues/861
