### ISSUE TITLE
Clear sessions does not work on Pharo 4 - Seaside 3.2

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#864]
Work a little of your application the go to `localhost:XXX/status`.
You will have a button to clear the current sessions. If you click on it, error.

http://puu.sh/o6ZY8/a4896bc629.png

**Comment by jbrichau** [comment]
Actually, the clear sessions works. The error occurs because the session you are using has been cleared :)
This used to return a 404, which is somewhat more expected than an error. So... let me take a look why that happens now.

**Comment by jecisc** [comment]
I got the same debugger with an error using WASession≥≥#unregister.

**Comment by jbrichau** [comment]
That's strange because this is tested in `WAExipryFunctionalTest` which seems to work fine. Can you give me a trace?

**Comment by jbrichau** [comment]
A fix for this was now committed in Seaside-Session-JohanBrichau.185.

I keep this issue open because I suspect a better (more generic fix) can be done by implementing:

```
WAApplication>>keyFor: aRequestHandler ifAbsent: absentBlock
	^ aRequestHandler key
```
Which means that WASession>>basicUrl can be implemented as follows:

```
basicUrl
	| url |
	url := super basicUrl.
	self parent trackingStrategy addKey: key toUrl: url.
	^ url
```
Which also seems to fix the issue, but breaks some tests. So it's surely not a complete fix.

**Comment by marschall** [comment]
You're correct @jbrichau that's a really good idea. I'll commit that. Locally all tests are green so we'll see what breaks.

Name: Seaside-Session-pmm.187
Author: pmm
Time: 21 August 2016, 5:15:20.959547 pm
UUID: e0e303c6-730b-49fc-bf7f-a3bce4533dda
Ancestors: Seaside-Session-JohanBrichau.186

Clear sessions does not work on Pharo 4 - Seaside 3.2 #864
- https://github.com/SeasideSt/Seaside/issues/864
- simplify code
