### ISSUE TITLE
Seaside Rest OPTIONS support

### ISSUE THREAD

**Issue by pdebruic** [SeasideSt/Seaside#865]
OPTIONS requests are used in CORS https://en.wikipedia.org/wiki/Cross-origin_resource_sharing to determine what the servers permissions are at a url before sending the actual GET, POST, PUT etc request

**Comment by marschall** [comment]
Name: Seaside-REST-Core-pmm.62
Author: pmm
Time: 19 August 2016, 12:21:38.711916 pm
UUID: fc9e5960-31d4-4139-b0a7-6e8f060d6616
Ancestors: Seaside-REST-Core-pmm.61

Seaside Rest OPTIONS support
https://github.com/SeasideSt/Seaside/issues/865

Name: Seaside-Tests-REST-Core-pmm.35
Author: pmm
Time: 19 August 2016, 12:22:08.692636 pm
UUID: 282b9c02-4c63-4bec-b198-7fe72aa31ab9
Ancestors: Seaside-Tests-REST-Core-pmm.34

Seaside Rest OPTIONS support
https://github.com/SeasideSt/Seaside/issues/865
