### ISSUE TITLE
Seaside control panel is not Pharo 6 compatible

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#869]
Seaside Control Panel depend on NewList, but NewList was removed from Pharo 6. Now Pharo use FastTable.

**Comment by marschall** [comment]
Name: Seaside-Pharo-Tools-Spec-pmm.21
Author: pmm
Time: 22 August 2016, 4:37:52.313848 pm
UUID: 85609e41-bcb8-4fb5-b954-58e32b637764
Ancestors: Seaside-Pharo-Tools-Spec-pmm.20

Seaside control panel is not Pharo 6 compatible #869
- https://github.com/SeasideSt/Seaside/issues/869
- use FastTableModel if available
