### ISSUE TITLE
Seaside-Examples should depend on JQuery

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#893]
When I load Seaside on Jenkins I get this:

WATodo class>>initialize (WADebugErrorHandler is Undeclared) 

WATodo>>renderTodosOn: (JSStream is Undeclared) 

WATodo>>renderTodosOn: (JSStream is Undeclared) 

WATodo>>renderTodosOn: (JSStream is Undeclared) 

WATodo>>renderTodosOn: (JSStream is Undeclared) 

WATodo>>renderTodosOn: (JSStream is Undeclared) 

WATodo>>renderTodosOn: (JSStream is Undeclared) 

WATodo>>renderTodosOn: (JSStream is Undeclared) 

WATodo>>renderTodosOn: (JSStream is Undeclared) 

WATodo>>renderTodosOn: (JSStream is Undeclared) 

WATodo>>updateRoot: (JQDeploymentLibrary is Undeclared) 

Loaded -> Seaside-Examples-JohanBrichau.31 --- http://smalltalkhub.com/mc/Seaside/Seaside32/main/ --- cache

This is not an important issue but this is the only undeclared elements and it should be easy to correct :)

**Comment by marschall** [comment]
Name: ConfigurationOfSeaside3-pmm.311
Author: pmm
Time: 10 September 2016, 1:50:32.92198 pm
UUID: e066878d-1aa9-41e1-9542-769220964728
Ancestors: ConfigurationOfSeaside3-JohanBrichau.310

Seaside-Examples should depend on JQuery
- https://github.com/SeasideSt/Seaside/issues/893

Name: Seaside-Examples-pmm.35
Author: pmm
Time: 10 September 2016, 1:51:22.331653 pm
UUID: 46a176f6-f47f-44d7-8826-f7a7c6973b8a
Ancestors: Seaside-Examples-pmm.34

Seaside-Examples should depend on JQuery
- https://github.com/SeasideSt/Seaside/issues/893

**Comment by marschall** [comment]
Closed by #894
