### ISSUE TITLE
Squeak-trunk not supported

### ISSUE THREAD

**Issue by fniephaus** [SeasideSt/Seaside#902]
Hi,
Someone [mentioned on the Squeak mailing list](http://forum.world.st/MNU-Character-gt-gt-greaseInteger-when-loading-Seaside-in-Squeak-Trunk-td4922096.html) that Seaside does not load in a current `Squeak-trunk` image. I believe `Squeak-trunk` currently has a version number of `Squeak6.0alpha`, so at least the [baseline](https://github.com/SeasideSt/Seaside/blob/6754ec6aa8da0502b45cbc269d604f9ba381cd0a/repository/BaselineOfSeaside3.package/BaselineOfSeaside3.class/instance/baselinesqueak..st#L12) needs to be adjusted I guess.

Is there another reason why `Squeak-trunk` is currently not supported?

**Comment by jbrichau** [comment]
Hi @fniephaus 

Sorry for the long wait

I can add it, but as always, someone needs to support it. 
I will give it a try. Is this still Squeak6.0alpha ? Or should I now try adding Squeak 6?

**Comment by fniephaus** [comment]
I think the baseline only really needs an additional `#'squeak6.x'`. Thanks!

**Comment by jbrichau** [comment]
I added Squeak trunk to the dev branch of Grease (we first need to make Grease work there before we can tackle Seaside).
https://travis-ci.org/SeasideSt/Grease/jobs/236319065

**Comment by krono** [comment]
I'm on it, please assign me

**Comment by marschall** [comment]
We currently build Squeak trunk, the only failing test is `WAPharoDebuggerTest >> #testNamedTempAt` which I can not reproduce locally.

**Comment by krono** [comment]
Sorry, I have to defer this; time is too tight at the moment, maybe Fabio can help

**Comment by fniephaus** [comment]
@jbrichau Sorry, I've lost track of this... has the issue been resolved in the meantime?

**Comment by jbrichau** [comment]
Hi @fniephaus 
No problem. It appears to work now: https://travis-ci.org/github/SeasideSt/Grease/jobs/688029228

**Comment by fniephaus** [comment]
Great! Thanks for confirming.
