### ISSUE TITLE
Does #attributeAt:put: works properly with booleans?

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#903]
If I use #attributeAt:put: with a boolean, the html generated does not contains a boolean but a string with the attribute name.

For example if I do `myTag attributeAt: 'toto' put: true` I get `<myTag toto="toto"></myTag>`.

But if I do  `myTag attributeAt: 'toto' put: 'true'` I get `<myTag toto="true"></myTag>`.

Is that the expected behaviour?

I used Seaside release3.2 on Pharo6.

**Comment by jbrichau** [comment]
Yes, this is because of the standard: http://stackoverflow.com/questions/4139786/what-does-it-mean-in-html-5-when-an-attribute-is-a-boolean-attribute

**Comment by jbrichau** [comment]
Related: https://github.com/SeasideSt/Seaside/issues/823
