### ISSUE TITLE
JQuery 3.0.0 is out

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#908]
https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

It would be cool to add it to a FileLibrary

**Comment by seandenigris** [comment]
It's now up to 3.3.1. 

[From the Seaside Book](http://book.seaside.st/book/web-20/jquery): 

> The Smalltalk side of the integration is automatically built from the excellent jQuery documentation, so you can be sure that the integration is up-to-date and feature-complete.


Thus it seems it should be straightforward to updating to the latest jQuery. What is the generation process?

**Comment by jbrichau** [comment]
Proposal to decouple the jQuery and Seaside versions in #1022

**Comment by jbrichau** [comment]
Updated the jQuery binding to 3.1.3 in 87f751380b16b870510efc7d24238d834a1c1bba
