### ISSUE TITLE
WAUrl can't parse query fields with no value

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Seaside#909]
The following fails

```smalltalk
WAUrl absolute: '/Buchhaltung?_s=F4N82ZReQEV2M1cP&_k=spf8TDq4kzHfrPCi&48&searchText=kas'
```

**Comment by marschall** [comment]
Name: Seaside-Core-pmm.881
Author: pmm
Time: 28 February 2017, 7:06:33.593602 pm
UUID: 9d4d12c2-baa3-4a64-97d6-0064ebf543af
Ancestors: Seaside-Core-pmm.880

WAUrl can't parse query fields with no value
- https://github.com/SeasideSt/Seaside/issues/909

Name: Seaside-Tests-Core-pmm.313
Author: pmm
Time: 28 February 2017, 7:07:10.697862 pm
UUID: dd92488a-4aaf-435e-b598-cac494f361a0
Ancestors: Seaside-Tests-Core-pmm.312

WAUrl can't parse query fields with no value
- https://github.com/SeasideSt/Seaside/issues/909

**Comment by marianopeck** [comment]
Uffff yes...it looks like the exact same issue and exact same fix...

**Comment by marschall** [comment]
Reopened, probably something went wrong with the sync
