### ISSUE TITLE
#noAutocomplete should also be understood by inputs

### ISSUE THREAD

**Issue by jecisc** [SeasideSt/Seaside#911]
In Seaside it is possible to send #noAutocomplete on a form. It would be good to also have this possibility on inputs. 

https://www.w3schools.com/tags/att_input_autocomplete.asp

**Comment by theseion** [comment]
Don't reference w3schools ;) They suck. Otherwise, I agree. I have a custom extension for that in my apps.

**Comment by marschall** [comment]
That's probably the spec we want:
https://html.spec.whatwg.org/#autofilling-form-controls:-the-autocomplete-attribute
