### ISSUE TITLE
Error when uploading zero byte long files

### ISSUE THREAD

**Issue by philippeback** [SeasideSt/Seaside#912]
![image](https://cloud.githubusercontent.com/assets/2128441/24547707/7afbaf4c-1611-11e7-8429-ec2e47b63637.png)

due to

![image](https://cloud.githubusercontent.com/assets/2128441/24547723/85a5e30e-1611-11e7-8657-83ec57559966.png)

Fix:

![image](https://cloud.githubusercontent.com/assets/2128441/24547738/93de7c4c-1611-11e7-9cf0-9e27213f43e4.png)

**Comment by marschall** [comment]
Zinc-Seaside is not directly maintained by the Seaside project. I sent Zinc-Seaside-pmm.47 with a fix to the maintainer of Zinc.

**Comment by svenvc** [comment]
Accepted upstream:

````
Name: Zinc-Seaside-SvenVanCaekenberghe.47
Author: SvenVanCaekenberghe
Time: 26 September 2017, 2:30:51.513022 pm
UUID: be672795-7816-0d00-89ce-240208d6220e
Ancestors: Zinc-Seaside-SvenVanCaekenberghe.46

Add a guard to ZnZincServerAdaptor>>#convertMultipartFileField: to handle empty POST uploads (thx Philippe Back)
````

with a slight variation

````
convertMultipartFileField: part  
	| file |
	(file := WAFile new)
		fileName: part fileName;
		contentType: part contentType printString;
		contents: (part hasEntity ifTrue: [ part contents asByteArray ] ifFalse: [ #[] ]).
	^ file
````
