### ISSUE TITLE
Make WAHtmlRoot configurable

### ISSUE THREAD

**Issue by theseion** [SeasideSt/Seaside#920]
I need WAHtmlRoot to be configurable so I can override certain methods.

**Comment by marschall** [comment]
Do you mean the one created in `WARenderPhaseContinuation`?

**Comment by theseion** [comment]
Yes.

**Comment by marschall** [comment]
You could always just provide your own render phase continuation, AFAIK this is already customizable.

**Comment by theseion** [comment]
Of course! Stupid. Thanks for clearing that up.
