### ISSUE TITLE
WADynamicVariable should inherit from GRDynamicVariable

### ISSUE THREAD

**Issue by theseion** [SeasideSt/Seaside#923]
[edit by Johan for later reference]
The implementation of WADynamicVariable moved to Grease to allow platform-specific optimizations
[/edit]

**Comment by theseion** [comment]
@marschall Proposal for this change:
1. all subclasses of WADynamicVariable now inherit from GRDynamicVariable
2. WADynamicVariable now inherits from GRDynamicVariable
3. WADynamicVariable class>>defaultValue will be removed (replaced by GRDynamicVariable>>default)

Does that sound ok?

**Comment by marschall** [comment]
1. ✔
2. ✔
3. Could we implement `WADynamicVariable >> #default` as `self class defaultValue` so that existing users keep working?

**Comment by theseion** [comment]
Done. See PR #926
