### ISSUE TITLE
Missing some changelog in the wiki

### ISSUE THREAD

**Issue by rejurime** [SeasideSt/Seaside#928]
In the [Wiki](https://github.com/SeasideSt/Seaside/wiki) I can't find the changelog for the release [v3.2.2](https://github.com/SeasideSt/Seaside/releases/tag/v3.2.2) and [v3.2.1](https://github.com/SeasideSt/Seaside/releases/tag/v3.2.1).
The changelogs jump from the [v3.2.0](https://github.com/SeasideSt/Seaside/wiki/Seaside320Changelog) to [v3.3.0](https://github.com/SeasideSt/Seaside/wiki/Seaside330Changelog).

**Comment by theseion** [comment]
Thanks. We'll see to it.

**Comment by theseion** [comment]
Added changelogs for 3.2.1, 3.2.2 and 3.2.4.
