### ISSUE TITLE
Support for Dolphin Smalltalk 7

### ISSUE THREAD

**Issue by rejurime** [SeasideSt/Seaside#929]
Is there any plan to add support for [Dolphin Smalltalk 7](https://github.com/dolphinsmalltalk/Dolphin)?
Because in Seaside web the [Dolphin Smalltalk](http://www.seaside.st/download/dolphin) section is for Seaside 3.0 and Dolphin Smalltalk 6.1.

**Comment by marschall** [comment]
We do not have any concrete plans to build a port for Dolphin Smalltalk 7. However we are not opposed to the idea. If somebody wants to step up we would surely provide support in the form of answering questions and generally providing know-how through the mailing list.

The topic has come up from time to time but so far nobody has stepped up. If somebody is interested Camp Smalltalk at ESUG is generally a good place to get in touch with people.
