### ISSUE TITLE
Bug in URL parsing that affected Ajax callbacks in GemStone

### ISSUE THREAD

**Issue by marianopeck** [SeasideSt/Seaside#932]
In GemStone 3.3 and 3.4 (at least) when using JQAjax >> script:  withOUT the line "self cache: true"  (which is the current latest state of seaside), the AJAX URLs are generated with something like this:

       '/reps?_s=eDS_xgsDW-eVq1Ki&_k=VjtmcpSz91iFIGsw&94&_=1499735755608

When in `requestUrlFor:` we parse the URL we get bad results:

        (WAUrl absolute: '/reps?_s=eDS_xgsDW-eVq1Ki&_k=VjtmcpSz91iFIGsw&94&_=1499735755608') queryFields ->aWARequestFields('_s'->'eDS_xgsDW-eVq1Ki' '_k'->'VjtmcpSz91iFIGsw' '94&_'->'' '_'->'1499735755608')

When that should have been:

         (WAUrl absolute: '/reps?_s=eDS_xgsDW-eVq1Ki&_k=VjtmcpSz91iFIGsw&94&_=1499735755608') 	queryFields -> aWARequestFields('_s'->'eDS_xgsDW-eVq1Ki' '_k'->'VjtmcpSz91iFIGsw' '94'->nil '_'->'1499735755608')

It seems to be a problem in the query parsing code in `WAUr>>#parseQuery:from:to:`

It doesn't check if the nameEnd is less than the parameterEnd, only the queryEnd.  So when an unnamed query parameter isn't last in the series of queries (like the callback parameter that precedes the cache busting parameter) then things aren't parsed properly.

   		WAUrl>>parseQuery: aString from: queryStart to: queryEnd
		| parameterStart |
		parameterStart := queryStart.
		[ parameterStart > 0 and: [ parameterStart < queryEnd ] ]
		 whileTrue: [
		   | nameEnd parameterEnd |
		   nameEnd := aString indexOf: $= startingAt: parameterStart.
		   parameterEnd := aString indexOf: $& startingAt: parameterStart.
		   parameterEnd := parameterEnd > 0
		     ifTrue: [ parameterEnd min: queryEnd ]
		     ifFalse: [ queryEnd ].
		   (nameEnd > 0 and: [ nameEnd < parameterEnd  ])
		     ifTrue: [
		       self
		         addField:
		           (self class decodePercentAndPlus: aString from: parameterStart to: nameEnd)
		         value:
		           (self class decodePercentAndPlus: aString from: nameEnd + 1 to: parameterEnd) ]
		     ifFalse: [
		       self
		         addField:
		           (self class decodePercentAndPlus: aString from: parameterStart to: parameterEnd) ].
		   parameterStart := parameterEnd + 1 ]

I will see if I can make a PR soon.

**Comment by jbrichau** [comment]
Is https://github.com/SeasideSt/Seaside/issues/909 related? The same?

**Comment by jbrichau** [comment]
@marianopeck Sorry that I was not able to relate your issue earlier on to this one.
I'll make a bugfix release asap.

**Comment by marianopeck** [comment]
@jbrichau no problem...it was really hard to track it down up to discover what was broken. It was impossible to figure out.
