### ISSUE TITLE
Programmatically changing the cache configuration requires to reinitialize the cache

### ISSUE THREAD

**Issue by jbrichau** [SeasideSt/Seaside#937]
Mariano remarks that it's not intuitive that you need to reinitialize the cache after changing its expiration configuration: http://lists.squeakfoundation.org/pipermail/seaside/2017-July/032792.html

Perhaps specific methods on `WAAdmin` should exist to set the configuration values for the cache, such that cache is reset. Something like:

```
WAAdmin>>changeCacheConfigurationIn: aBlock for: app
    aBlock value: app configuration.
    app cache: (app createCache)
```

**Comment by marschall** [comment]
I'll simply add a `#initializeCache` a method.

I am not happy with the `#changeCacheConfigurationIn:for:` selector.
* I believe the block should be the last argument.
* It allows to change any configuration, not just the cache configuration.
* It doesn't really seem to add that much value.
