### ISSUE TITLE
Seaside-REST loads Seaside-Component

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Seaside#958]
When loading the `REST` group the `Core` group is loaded as well. This includes `Canvas`, `Session`, `Component`, `Flow` and `Widgets`. I would not expect these to be loaded as well, the only one I would expect is `Seaside-Tools-Core`. Which brings me to the next one which is that `Seaside-Tools-Core` depends on `Seaside-Component`, `Seaside-RenderLoop` and `Seaside-Session`.

I see two options here:
1. make core just be `Seaside-Core` and `Seaside-Tools-Core`, introduce a new `Component` group that replaces the existing `Core` group
1. remove the dependency from `REST` to `Core`

**Comment by jbrichau** [comment]
Sounds like a plan.

**Comment by marschall** [comment]
Which you do you prefer? 1. or 2.?

**Comment by jbrichau** [comment]
Ha. I was going with 1 actually. :)
Read a bit too quickly: how would you tackle option 2 ? I assume it is using something from Core?

**Comment by marschall** [comment]
It is using `Seaside-Core` but that's already expressed in a dependency.

**Comment by marschall** [comment]
Looking at our Baseline we have a `Base` group that's identical to `Core`. I could remove component from base and make `REST` depend on `Base`. That way users of `Core` are not affected.

**Comment by marschall** [comment]
Fixed by #975

**Comment by marschall** [comment]
Looks like this got broken again by 47476bf3a05dbcb4158d1db93ab552081cc057e3
