### ISSUE TITLE
Untracked dependency from Seaside-Environment to Seaside-Development

### ISSUE THREAD

**Issue by marschall** [SeasideSt/Seaside#959]
`Seaside-Environment` has an untracked dependency to `Seaside-Development` because `WAEnvrionment >> #configureApplicationExceptionHandlingDefaults` refers to `WAWalkbackErrorHandler`.

`WAWalkbackErrorHandler` registers itself in `WAWalkbackErrorHandler class >> #initialize`. We should probably register a `WAErrorHandler` there. OTOH `WAErrorHandler` is the default anyway so maybe we should move the code to `WAWalkbackErrorHandler `.

**Comment by jbrichau** [comment]
Looks good, but this might reduce the dev experience even further. We had numerous people being confused about why the WADebugHandler is not the default when they download Seaside...
But that's maybe another issue?

**Comment by marschall** [comment]
`WAWalkbackErrorHandler` should install itself when loaded so the experience should stay the same.

**Comment by marschall** [comment]
Fixed by #975
