### ISSUE TITLE
Seaside-Swagger-Core does not compile in GemStone 2.4.8

### ISSUE THREAD

**Issue by dalehenrich** [SeasideSt/Seaside#983]
We're getting a `'Compile error in Class: #''WASwaggerUIFileLibrary'' method: explorericonsPng` [on travis](https://travis-ci.org/dalehenrich/Seaside/jobs/330545373#L2319) and it looks like the problem is that GemStone 2.4 has a non-standard ByteArray literal ... My inclination is to change BaselineOfSeaside3>>baselinerest:  so that Swagger will only be loaded in GemStone 3.x .. Only 2.4.8 is failing...

I have a [pending checkin to add some tODE scripts to the Seaside checkout ... still in development](https://github.com/dalehenrich/Seaside/tree/dkh-patch-2) where I will apply this patch and see if I can get the tests to pass ...

**Comment by dalehenrich** [comment]
Hmmm similar compile error showing up in [WAExamplesLibrary](https://travis-ci.org/dalehenrich/Seaside/jobs/331104314#L1707) ... I guess these builds have been failing for awhile now? Well I think I have a handle on the problem..... the examples failing to load is slightly more problematic than Swagger, but presumably Seaside 2.4 is tested for folks with existing stones running on 2.4 and they either don't load the Examples and Swagger or have patched the issue themselves

**Comment by dalehenrich** [comment]
Upon further review, the whole Welcome page is pretty tightly coupled, so to get the tests to pass, we'd need to wire out the Welcome page and Examples for GemStone 2.4.x ... AFAIK GemStone 2.4.x is still being used for production Seaside apps (that don't use Examples or the Welcome page) so I still think this is a kosher approach...

**Comment by dalehenrich** [comment]
Well now that the load issues are resolved, there are still a [bunch of failing tests](https://travis-ci.org/dalehenrich/Seaside/jobs/331501771#L1993-L1996) so perhaps at this point 2.4.8 should be put into "expected failures" category ...

**Comment by marschall** [comment]
In agreement with @dalehenrich Seaside 3.3.0 does no longer support GemStone 2.4.

Removed from Travis in deda3150eeb7d5250bd36010443bdb695aa84c38
We should probably check the configurations as well.
