### ISSUE TITLE
GRPharoPlatform>>bindingOf: uses #name

### ISSUE THREAD

**Issue by macta** [SeasideSt/Seaside#986]
When loading the PotsDam seaside tutorial it calls bindingOf: when loading and you get a pharo error:

#name called from GRPharoPlatform>>#bindingOf: has been deprecated.
Implement your own domain representation of an object, or use #asString or #printString instead.

Tiny fix I think - name is being given to the users...

**Comment by marschall** [comment]
Can you provide more information:
- Which version of Seaside?
- Which Smalltalk dialect in which version?

**Comment by marschall** [comment]
Closing because not enough information to reproduce was provided. Feel free to reopen with a way to reproduce.
